// Entitlements are verified by the API. No credentials or admin secrets are stored in the extension.
const MHPAccess=(()=>{
 const BASE='https://maps-hunter-pro-api.anas98gha.workers.dev';
 async function saved(){const s=await chrome.storage.local.get(['mhp_license','mhp_device','mhp_entitlement']);if(!s.mhp_device){s.mhp_device=crypto.randomUUID();await chrome.storage.local.set({mhp_device:s.mhp_device})}return s}
 async function request(path,x){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(BASE+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(x),signal:c.signal});let d={};try{d=await r.json()}catch{}if(!r.ok||d.ok===false){const code=d.error||'LICENSE_CHECK_FAILED';const next=new Date();next.setUTCHours(24,0,0,0);throw new Error(code==='DAILY_LIMIT_REACHED'?`Daily limit reached. Resume after ${next.toISOString().replace('.000Z','Z')}.`:code)}return d}catch(err){err.accessError=true;throw err}finally{clearTimeout(timer)}}
 async function verify(s){const d=await request('/api/license/validate',{licenseKey:s.mhp_license,deviceId:s.mhp_device});await chrome.storage.local.set({mhp_entitlement:{...d,checkedAt:Date.now()}});return d}
 async function validate(){const s=await saved();if(!s.mhp_license){const err=new Error('Activate your license before starting a search.');err.accessError=true;throw err}return verify(s)}
 async function status(){const s=await saved();if(!s.mhp_license)return {licenseKey:'',entitlement:null};try{return {licenseKey:s.mhp_license,entitlement:await verify(s)}}catch(err){return {licenseKey:s.mhp_license,entitlement:s.mhp_entitlement||null,validationError:err.message||String(err)}}}
 return {validate,status,async save(licenseKey){const code=String(licenseKey||'').trim().toUpperCase();if(!code)throw Object.assign(new Error('ACTIVATION_CODE_REQUIRED'),{accessError:true});const s=await saved();const d=await request('/api/license/validate',{licenseKey:code,deviceId:s.mhp_device});await chrome.storage.local.set({mhp_license:code,mhp_entitlement:{...d,checkedAt:Date.now()}});return {ok:true,...d}},async consume(requestId){const s=await saved();const d=await request('/api/usage/consume',{licenseKey:s.mhp_license,deviceId:s.mhp_device,requestId,amount:1});await chrome.storage.local.set({mhp_entitlement:{...d,checkedAt:Date.now()}});return d}};
})();
