(()=>{
'use strict';
let state={leads:[],running:false,paused:false,phase:'Ready',status:'Ready.'};
let leads=[];
let toastTimer;
const SETTINGS_KEY='mhp_panel_settings';
const SEARCH_MEMORY_KEY='mhp_last_search';
const SETTINGS_DEFAULTS={workers:3,autoOpenResults:true,rememberSearch:true};
let settings={...SETTINGS_DEFAULTS};
const $=id=>document.getElementById(id);
const send=payload=>new Promise(resolve=>{try{chrome.runtime.sendMessage(payload,r=>resolve(r||{}))}catch(e){resolve({ok:false,error:e.message||String(e)})}});
function openPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav-tab').forEach(b=>b.classList.toggle('active',b.dataset.page===id));}
function toast(msg){const el=$('toast');if(!el)return;el.textContent=String(msg||'');el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
const tagState={keyword:[],city:[]};
function cleanTag(v){return String(v||'').trim().replace(/\s+/g,' ')}
function inputFor(kind){return $(kind==='keyword'?'keywordInput':'cityInput')}
function listFor(kind){return $(kind==='keyword'?'keywordTags':'cityTags')}
function renderTags(kind){const box=listFor(kind);if(!box)return;box.innerHTML=tagState[kind].map((value,index)=>`<span class="tag-chip"><b>${escapeHtml(value)}</b><button type="button" data-tag-remove="${kind}" data-tag-index="${index}" aria-label="Remove ${escapeHtml(value)}">×</button></span>`).join('')}
function addTag(kind,value){value=cleanTag(value);if(!value)return false;const exists=tagState[kind].some(x=>x.toLocaleLowerCase()===value.toLocaleLowerCase());if(exists)return false;if(kind==='keyword')tagState.keyword=[value];else tagState.city.push(value);renderTags(kind);return true}
function commitInput(kind){const input=inputFor(kind);if(!input)return false;const raw=cleanTag(input.value);if(!raw)return false;if(kind==='city')raw.split(/[\n,;،]+/).map(cleanTag).filter(Boolean).forEach(v=>addTag(kind,v));else addTag(kind,raw);input.value='';return true}
function removeTag(kind,index){if(!tagState[kind]||index<0||index>=tagState[kind].length)return;tagState[kind].splice(index,1);renderTags(kind);inputFor(kind)?.focus()}
function setupTagEditor(kind){const input=inputFor(kind),editor=$(kind==='keyword'?'keywordEditor':'cityEditor');if(!input)return;input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();commitInput(kind)}else if(e.key==='Backspace'&&!input.value&&tagState[kind].length){e.preventDefault();removeTag(kind,tagState[kind].length-1)}});input.addEventListener('blur',()=>{if(cleanTag(input.value))commitInput(kind)});editor?.addEventListener('click',()=>input.focus())}
function localGet(key){return new Promise(resolve=>{try{chrome.storage.local.get([key],obj=>resolve(obj?.[key]))}catch(e){resolve(undefined)}})}
function localSet(obj){return new Promise(resolve=>{try{chrome.storage.local.set(obj,()=>resolve(true))}catch(e){resolve(false)}})}
function localRemove(key){return new Promise(resolve=>{try{chrome.storage.local.remove(key,()=>resolve(true))}catch(e){resolve(false)}})}
function normalizeSettings(raw){raw=raw&&typeof raw==='object'?raw:{};return{workers:Math.max(1,Math.min(6,Number(raw.workers||SETTINGS_DEFAULTS.workers))),autoOpenResults:raw.autoOpenResults!==false,rememberSearch:raw.rememberSearch!==false}}
function syncSettingsForm(){if($('settingsWorkers'))$('settingsWorkers').value=String(settings.workers);if($('settingsAutoResults'))$('settingsAutoResults').checked=settings.autoOpenResults;if($('settingsRemember'))$('settingsRemember').checked=settings.rememberSearch}
function readSettingsForm(){return normalizeSettings({workers:Number($('settingsWorkers')?.value||3),autoOpenResults:$('settingsAutoResults')?.checked===true,rememberSearch:$('settingsRemember')?.checked===true})}
async function restoreLastSearch(){if(!settings.rememberSearch)return;const saved=await localGet(SEARCH_MEMORY_KEY);if(!saved||typeof saved!=='object')return;tagState.keyword=[];tagState.city=[];if(cleanTag(saved.keyword))addTag('keyword',saved.keyword);for(const city of Array.isArray(saved.cities)?saved.cities:[])addTag('city',city);renderTags('keyword');renderTags('city')}
async function rememberCurrentSearch(keyword,cities){if(!settings.rememberSearch)return;await localSet({[SEARCH_MEMORY_KEY]:{keyword,cities:[...cities]}})}
async function loadSettings(){settings=normalizeSettings(await localGet(SETTINGS_KEY));syncSettingsForm();await restoreLastSearch()}
async function saveSettings(){settings=readSettingsForm();await localSet({[SETTINGS_KEY]:settings});if(!settings.rememberSearch)await localRemove(SEARCH_MEMORY_KEY);else{commitInput('keyword');commitInput('city');if(tagState.keyword[0]||tagState.city.length)await rememberCurrentSearch(tagState.keyword[0]||'',tagState.city)}syncSettingsForm();toast('Settings saved.')}
async function resetSettings(){settings={...SETTINGS_DEFAULTS};await localSet({[SETTINGS_KEY]:settings});syncSettingsForm();toast('Settings reset to defaults.')}
function fmtDate(v){if(!v)return 'No expiry';const raw=String(v);const d=new Date(raw.includes('T')?raw:raw.replace(' ','T')+'Z');return Number.isNaN(d.getTime())?raw:d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
function errorLabel(code){const map={INVALID_LICENSE:'Invalid activation code.',LICENSE_REVOKED:'This code has been revoked.',LICENSE_EXPIRED:'This code has expired.',DEVICE_LIMIT_REACHED:'This code has reached its device limit.',DEVICE_BLOCKED:'This device is blocked.',ACTIVATION_CODE_REQUIRED:'Enter an activation code first.',DAILY_LIMIT_REACHED:'Daily result limit reached.'};return map[code]||String(code||'Activation failed.')}
function isNetworkError(text){return /fetch|network|abort|failed/i.test(String(text||''))}
async function refreshLicense(showChecking=true){const box=$('licenseStatusBox');if(showChecking&&box){box.className='activation-state';box.innerHTML='<strong>Checking activation…</strong><span>Please wait.</span>'}const access=await send({type:'GET_LICENSE'});const input=$('licenseKey');if(input&&access.licenseKey&&!input.value)input.value=access.licenseKey;renderLicense(access);return access;}
function renderLicense(access){const box=$('licenseStatusBox'),chip=$('licenseChip'),stateText=$('licenseStateText'),expires=$('expiresText');const ent=access?.entitlement,lic=ent?.license||{};if(ent?.valid){const date=lic.owner?'No expiry':fmtDate(lic.expiresAt);if(box){box.className='activation-state ok';box.innerHTML=`<strong>${lic.owner?'Owner Access active':'Activation successful'}</strong><span>${lic.owner?'Permanent owner access.':`Expires ${date}`}</span>`}if(chip){chip.className='license-chip ok';chip.textContent='Activated'}if(stateText)stateText.textContent='Active';if(expires)expires.textContent=date;return;}if(access?.licenseKey&&access?.validationError){const offline=isNetworkError(access.validationError),label=offline?'Cannot reach activation server':errorLabel(access.validationError);if(box){box.className='activation-state bad';box.innerHTML=`<strong>${label}</strong><span>${offline?'Check your internet connection and try again.':'Enter a valid code or contact support.'}</span>`}if(chip){chip.className='license-chip bad';chip.textContent=offline?'Offline':'Not active'}if(stateText)stateText.textContent=offline?'Offline':'Invalid';if(expires)expires.textContent='—';return;}if(box){box.className='activation-state bad';box.innerHTML='<strong>Not activated</strong><span>Enter the code you received after payment confirmation.</span>'}if(chip){chip.className='license-chip bad';chip.textContent='Not activated'}if(stateText)stateText.textContent='Inactive';if(expires)expires.textContent='—';}
async function activateCode(){const code=String($('licenseKey')?.value||'').trim().toUpperCase();if(!code)return toast('Enter your activation code.');const btn=$('saveLicense');if(btn)btn.disabled=true;const res=await send({type:'SET_LICENSE',licenseKey:code});if(btn)btn.disabled=false;if(!res?.ok){toast(errorLabel(res?.error));await refreshLicense(false);return}toast('Activation successful.');await refreshLicense(false);}
async function startSearch(){if(state.paused){const r=await send({type:'RESUME_SCAN'});if(!r?.ok)return toast(errorLabel(r?.error));return}commitInput('keyword');commitInput('city');const keyword=tagState.keyword[0]||'',cities=[...tagState.city];if(!keyword)return toast('Enter a business keyword.');if(!cities.length)return toast('Add at least one city.');await rememberCurrentSearch(keyword,cities);const access=await refreshLicense(false);if(!access?.entitlement?.valid){openPage('licensePage');return toast('Activate the tool before starting a search.')}const btn=$('startBtn');if(btn)btn.disabled=true;const r=await send({type:'START_SCAN',keyword,cities,maxWorkers:Number(settings.workers||3),scanFirst:true});if(btn)btn.disabled=false;if(!r?.ok){toast(errorLabel(r?.error));if(/LICENSE|ACTIVATION|DEVICE|LIMIT/i.test(String(r?.error||'')))openPage('licensePage');}}
async function stopSearch(){const btn=$('stopBtn');if(btn)btn.disabled=true;const r=await send({type:'SKIP_SCAN_CITY'});if(!r?.ok){if(btn)btn.disabled=false;return toast(r?.error||'Could not stop scan.')}toast(r.queued?`Scan stopped. Extracting ${r.queued} collected places…`:'Scan stopped. Moving to the next step…')}
async function stopAll(){const btn=$('stopAllBtn');if(btn)btn.disabled=true;const r=await send({type:'STOP_ALL'});if(!r?.ok){if(btn)btn.disabled=false;return toast(r?.error||'Could not stop all work.')}toast(`Stopped. Kept ${Number(r.saved||0)} completed leads.`)}
async function skipCity(){const r=await send({type:'SKIP_CITY'});if(!r?.ok)toast(r?.error||'Could not skip city.');else toast(r.done?'No more cities.':`Opening ${r.next||'next city'}…`)}
async function clearResults(){if(!leads.length)return toast('No saved results.');const r=await send({type:'CLEAR_RESULTS'});if(r?.ok)toast('Results cleared.');}
function exportAction(action){if(!leads.length)return toast('No results to export.');const url=new URL(chrome.runtime.getURL('data.html'));if(action!=='sheet')url.searchParams.set('export',action);chrome.tabs.create({url:url.toString()})}
async function exportExcelDirect(){
  if(typeof MHPExport==='undefined')return toast('Excel exporter failed to load.');
  const payload=await send({type:'GET_EXPORT_DATA'});
  const exportLeads=Array.isArray(payload?.leads)?payload.leads:(Array.isArray(leads)?leads:[]);
  if(!exportLeads.length)return toast('No results to export.');
  const now=new Date(),pad=n=>String(n).padStart(2,'0'),stamp=`${now.getFullYear()}${pad(now.getMonth()+1)}${pad(now.getDate())}_${pad(now.getHours())}${pad(now.getMinutes())}`;
  try{
    const result=await MHPExport.xlsx(exportLeads,`maps_hunter_${stamp}.xlsx`,{
      search:[payload?.meta?.keyword,...(Array.isArray(payload?.meta?.cities)?payload.meta.cities:[])].filter(Boolean).join(' — ')
    });
    if(!result?.ok||!Number(result.rows))throw new Error('Excel contained no data rows.');
    toast(`Excel downloaded: ${result.rows} leads.`);
  }catch(e){console.error('Excel export failed',e);toast('Excel export failed.')}
}
function renderState(next){const previous=state||{};state=next||state;leads=Array.isArray(state.leads)?state.leads:leads;const total=leads.length,phones=leads.filter(x=>x.phone).length,emails=leads.filter(x=>x.email||x.emails).length,social=leads.filter(x=>x.facebook||x.instagram||x.socialLinks).length;$('leadCount').textContent=total;$('tabLeadCount').textContent=total;$('resultTotal').textContent=total;$('phoneCount').textContent=phones;$('emailCount').textContent=emails;$('socialCount').textContent=social;const running=Boolean(state.running),paused=Boolean(state.paused),phase=String(state.phase||'Ready');document.body.classList.toggle('is-running',running);$('phaseBadge').textContent=phase;$('statusTitle').textContent=running?(phase||'Working…'):paused?'Search paused':total?'Search complete':'Ready to search';$('statusText').textContent=state.status||'Enter a keyword and at least one city.';const queued=Number(state.queued||0),processed=Number(state.processed||0);$('progressBar').style.width=`${queued?Math.min(100,Math.round(processed/queued*100)):running?12:0}%`;$('startBtn').disabled=running;$('startBtn').querySelector('span').textContent=paused?'Resume Search':'Start Search';const scanning=running&&/Opening Maps|Collecting/i.test(phase);$('stopBtn').disabled=!scanning;$('skipCityBtn').disabled=!running;if($('stopAllBtn'))$('stopAllBtn').disabled=!(running||paused);renderRecent();if(Boolean(previous.running)&&!running&&phase==='Completed'&&settings.autoOpenResults)openPage('resultsPage');}
function renderRecent(){const box=$('recentResults');if(!box)return;const rows=leads.slice(-3).reverse();if(!rows.length){box.innerHTML='<div class="empty-state">Your latest businesses will appear here.</div>';return}box.innerHTML=rows.map(x=>`<div class="recent-item"><strong>${escapeHtml(x.name||'Unnamed business')}</strong><span>${escapeHtml(x.phone||x.address||'Saved')}</span></div>`).join('')}
function escapeHtml(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
async function init(){document.querySelectorAll('.nav-tab').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.page)));setupTagEditor('keyword');setupTagEditor('city');document.addEventListener('click',e=>{const btn=e.target.closest?.('[data-tag-remove]');if(btn)removeTag(btn.dataset.tagRemove,Number(btn.dataset.tagIndex))});$('startBtn').addEventListener('click',startSearch);$('stopBtn').addEventListener('click',stopSearch);$('stopAllBtn')?.addEventListener('click',stopAll);$('skipCityBtn').addEventListener('click',skipCity);$('clearBtn').addEventListener('click',clearResults);$('saveLicense').addEventListener('click',activateCode);$('excelBtn').addEventListener('click',exportExcelDirect);$('csvBtn').addEventListener('click',()=>exportAction('csv'));$('jsonBtn').addEventListener('click',()=>exportAction('json'));$('openSheetBtn').addEventListener('click',()=>exportAction('sheet'));$('saveSettingsBtn')?.addEventListener('click',saveSettings);$('resetSettingsBtn')?.addEventListener('click',resetSettings);$('licenseKey').addEventListener('keydown',e=>{if(e.key==='Enter')activateCode()});await loadSettings();const current=await send({type:'GET_STATE'});renderState(current||{});await refreshLicense();chrome.runtime.onMessage.addListener(msg=>{if(msg?.type==='STATE_UPDATE')renderState(msg.state||{})});chrome.storage?.onChanged?.addListener((changes,area)=>{if(area==='local'&&changes.mhp_license)refreshLicense(false)});}
document.addEventListener('DOMContentLoaded',init);
})();
