(()=>{
'use strict';
let state={leads:[],running:false,paused:false,phase:'Ready',status:'Ready.'};
let leads=[];
let toastTimer;
const $=id=>document.getElementById(id);
const send=payload=>new Promise(resolve=>{try{chrome.runtime.sendMessage(payload,r=>resolve(r||{}))}catch(e){resolve({ok:false,error:e.message||String(e)})}});
function openPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav-tab').forEach(b=>b.classList.toggle('active',b.dataset.page===id));}
function toast(msg){const el=$('toast');if(!el)return;el.textContent=String(msg||'');el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function parseCities(){return [...new Set(String($('citiesInput')?.value||'').split(/[\n,;،]+/).map(x=>x.trim()).filter(Boolean))]}
function fmtDate(v){if(!v)return 'No expiry';const raw=String(v);const d=new Date(raw.includes('T')?raw:raw.replace(' ','T')+'Z');return Number.isNaN(d.getTime())?raw:d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}
function errorLabel(code){const map={INVALID_LICENSE:'Invalid activation code.',LICENSE_REVOKED:'This code has been revoked.',LICENSE_EXPIRED:'This code has expired.',DEVICE_LIMIT_REACHED:'This code has reached its device limit.',DEVICE_BLOCKED:'This device is blocked.',ACTIVATION_CODE_REQUIRED:'Enter an activation code first.',DAILY_LIMIT_REACHED:'Daily result limit reached.'};return map[code]||String(code||'Activation failed.')}
function isNetworkError(text){return /fetch|network|abort|failed/i.test(String(text||''))}
async function refreshLicense(showChecking=true){const box=$('licenseStatusBox');if(showChecking&&box){box.className='activation-state';box.innerHTML='<strong>Checking activation…</strong><span>Please wait.</span>'}const access=await send({type:'GET_LICENSE'});const input=$('licenseKey');if(input&&access.licenseKey&&!input.value)input.value=access.licenseKey;renderLicense(access);return access;}
function renderLicense(access){const box=$('licenseStatusBox'),chip=$('licenseChip'),stateText=$('licenseStateText'),expires=$('expiresText');const ent=access?.entitlement,lic=ent?.license||{};if(ent?.valid){const date=lic.owner?'No expiry':fmtDate(lic.expiresAt);if(box){box.className='activation-state ok';box.innerHTML=`<strong>${lic.owner?'Owner Access active':'Activation successful'}</strong><span>${lic.owner?'Permanent owner access.':`Expires ${date}`}</span>`}if(chip){chip.className='license-chip ok';chip.textContent='Activated'}if(stateText)stateText.textContent='Active';if(expires)expires.textContent=date;return;}if(access?.licenseKey&&access?.validationError){const offline=isNetworkError(access.validationError),label=offline?'Cannot reach activation server':errorLabel(access.validationError);if(box){box.className='activation-state bad';box.innerHTML=`<strong>${label}</strong><span>${offline?'Check your internet connection and try again.':'Enter a valid code or contact support.'}</span>`}if(chip){chip.className='license-chip bad';chip.textContent=offline?'Offline':'Not active'}if(stateText)stateText.textContent=offline?'Offline':'Invalid';if(expires)expires.textContent='—';return;}if(box){box.className='activation-state bad';box.innerHTML='<strong>Not activated</strong><span>Enter the code you received after payment confirmation.</span>'}if(chip){chip.className='license-chip bad';chip.textContent='Not activated'}if(stateText)stateText.textContent='Inactive';if(expires)expires.textContent='—';}
async function activateCode(){const code=String($('licenseKey')?.value||'').trim().toUpperCase();if(!code)return toast('Enter your activation code.');const btn=$('saveLicense');if(btn)btn.disabled=true;const res=await send({type:'SET_LICENSE',licenseKey:code});if(btn)btn.disabled=false;if(!res?.ok){toast(errorLabel(res?.error));await refreshLicense(false);return}toast('Activation successful.');await refreshLicense(false);}
async function startSearch(){if(state.paused){const r=await send({type:'RESUME_SCAN'});if(!r?.ok)return toast(errorLabel(r?.error));return}const keyword=String($('keyword')?.value||'').trim(),cities=parseCities();if(!keyword)return toast('Enter a business keyword.');if(!cities.length)return toast('Add at least one city.');const access=await refreshLicense(false);if(!access?.entitlement?.valid){openPage('licensePage');return toast('Activate the tool before starting a search.')}const btn=$('startBtn');if(btn)btn.disabled=true;const r=await send({type:'START_SCAN',keyword,cities,maxWorkers:Number($('workerCount')?.value||3),scanFirst:true,enrichWebsites:$('enrichWebsites')?.checked===true});if(btn)btn.disabled=false;if(!r?.ok){toast(errorLabel(r?.error));if(/LICENSE|ACTIVATION|DEVICE|LIMIT/i.test(String(r?.error||'')))openPage('licensePage');}}
async function stopSearch(){const r=await send({type:'STOP_SCAN'});if(!r?.ok)toast(r?.error||'Could not stop search.')}
async function skipCity(){const r=await send({type:'SKIP_CITY'});if(!r?.ok)toast(r?.error||'Could not skip city.');else toast(r.done?'No more cities.':`Opening ${r.next||'next city'}…`)}
async function clearResults(){if(!leads.length)return toast('No saved results.');const r=await send({type:'CLEAR_RESULTS'});if(r?.ok)toast('Results cleared.');}
function exportAction(action){if(!leads.length)return toast('No results to export.');const url=new URL(chrome.runtime.getURL('data.html'));if(action!=='sheet')url.searchParams.set('export',action);chrome.tabs.create({url:url.toString()})}
function renderState(next){state=next||state;leads=Array.isArray(state.leads)?state.leads:leads;const total=leads.length,phones=leads.filter(x=>x.phone).length,emails=leads.filter(x=>x.email||x.emails).length,social=leads.filter(x=>x.facebook||x.instagram||x.socialLinks).length;$('leadCount').textContent=total;$('tabLeadCount').textContent=total;$('resultTotal').textContent=total;$('phoneCount').textContent=phones;$('emailCount').textContent=emails;$('socialCount').textContent=social;const running=Boolean(state.running),paused=Boolean(state.paused);document.body.classList.toggle('is-running',running);$('phaseBadge').textContent=state.phase||'Ready';$('statusTitle').textContent=running?(state.phase||'Working…'):paused?'Search paused':total?'Search complete':'Ready to search';$('statusText').textContent=state.status||'Enter a keyword and at least one city.';const queued=Number(state.queued||0),processed=Number(state.processed||0);$('progressBar').style.width=`${queued?Math.min(100,Math.round(processed/queued*100)):running?12:0}%`;$('startBtn').disabled=running;$('startBtn').querySelector('span').textContent=paused?'Resume Search':'Start Search';$('stopBtn').disabled=!running;$('skipCityBtn').disabled=!running;renderRecent();}
function renderRecent(){const box=$('recentResults');if(!box)return;const rows=leads.slice(-3).reverse();if(!rows.length){box.innerHTML='<div class="empty-state">Your latest businesses will appear here.</div>';return}box.innerHTML=rows.map(x=>`<div class="recent-item"><strong>${escapeHtml(x.name||'Unnamed business')}</strong><span>${escapeHtml(x.phone||x.address||'Saved')}</span></div>`).join('')}
function escapeHtml(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
async function init(){document.querySelectorAll('.nav-tab').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.page)));$('startBtn').addEventListener('click',startSearch);$('stopBtn').addEventListener('click',stopSearch);$('skipCityBtn').addEventListener('click',skipCity);$('clearBtn').addEventListener('click',clearResults);$('saveLicense').addEventListener('click',activateCode);$('excelBtn').addEventListener('click',()=>exportAction('excel'));$('csvBtn').addEventListener('click',()=>exportAction('csv'));$('jsonBtn').addEventListener('click',()=>exportAction('json'));$('openSheetBtn').addEventListener('click',()=>exportAction('sheet'));$('licenseKey').addEventListener('keydown',e=>{if(e.key==='Enter')activateCode()});const current=await send({type:'GET_STATE'});renderState(current||{});await refreshLicense();chrome.runtime.onMessage.addListener(msg=>{if(msg?.type==='STATE_UPDATE')renderState(msg.state||{})});chrome.storage?.onChanged?.addListener((changes,area)=>{if(area==='local'&&changes.mhp_license)refreshLicense(false)});}
document.addEventListener('DOMContentLoaded',init);
})();
