// Minimal OOXML writer: ZIP entries are stored without compression, all scraped cells are strings.
// No formula evaluation, remote scripts, or third-party runtime dependencies.
const MHPExport=(()=>{
 const te=new TextEncoder();
 const xml=x=>String(x??'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 const table=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});
 function crc(a){let n=0xffffffff;for(const b of a)n=table[(n^b)&255]^(n>>>8);return (n^0xffffffff)>>>0}
 function zip(files){const local=[],central=[];let offset=0,centralSize=0;for(const [name,text]of Object.entries(files)){const nameBytes=te.encode(name),data=te.encode(text),c=crc(data),lh=new Uint8Array(30+nameBytes.length),lv=new DataView(lh.buffer);lv.setUint32(0,0x04034b50,true);lv.setUint16(4,20,true);lv.setUint32(14,c,true);lv.setUint32(18,data.length,true);lv.setUint32(22,data.length,true);lv.setUint16(26,nameBytes.length,true);lh.set(nameBytes,30);local.push(lh,data);const ch=new Uint8Array(46+nameBytes.length),cv=new DataView(ch.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint32(16,c,true);cv.setUint32(20,data.length,true);cv.setUint32(24,data.length,true);cv.setUint16(28,nameBytes.length,true);cv.setUint32(42,offset,true);ch.set(nameBytes,46);central.push(ch);centralSize+=ch.length;offset+=lh.length+data.length}const end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,central.length,true);v.setUint16(10,central.length,true);v.setUint32(12,centralSize,true);v.setUint32(16,offset,true);return new Blob([...local,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
 const cols=[['name','Business Name'],['phone','Phone'],['address','Address'],['website','Website'],['email','Email'],['rating','Rating'],['reviews','Reviews'],['category','Category'],['mapsUrl','Google Maps'],['searchCity','Search City'],['facebook','Facebook'],['instagram','Instagram'],['linkedin','LinkedIn'],['twitter','Twitter/X'],['youtube','YouTube'],['tiktok','TikTok']];
 function workbook(leads){const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';const data=[cols.map(c=>c[1]),...leads.map(l=>cols.map(([k])=>l[k]||(k==='email'?l.emails:'')||''))];const links=[];const sheetRows=data.map((row,i)=>'<row r="'+(i+1)+'">'+row.map((s,j)=>{const cell=String.fromCharCode(65+j)+(i+1);if(i&&/^https?:\/\//i.test(String(s)))links.push({cell,url:s});return '<c r="'+cell+'" s="'+(i?'0':'1')+'" t="inlineStr"><is><t xml:space="preserve">'+xml(s)+'</t></is></c>'}).join('')+'</row>').join('');return zip({
 '[Content_Types].xml':'<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>',
 '_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
 'xl/workbook.xml':'<workbook xmlns="'+ns+'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Leads" sheetId="1" r:id="rId1"/></sheets></workbook>',
 'xl/_rels/workbook.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
 'xl/styles.xml':'<styleSheet xmlns="'+ns+'"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf numFmtId="49"/><xf fontId="1" applyFont="1"/></cellXfs></styleSheet>',
 'xl/worksheets/sheet1.xml':'<worksheet xmlns="'+ns+'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="16" width="24" customWidth="1"/></cols><sheetData>'+sheetRows+'</sheetData><autoFilter ref="A1:P'+data.length+'"/>'+(links.length?'<hyperlinks>'+links.map((l,i)=>'<hyperlink ref="'+l.cell+'" r:id="rId'+(i+1)+'"/>').join('')+'</hyperlinks>':'')+'</worksheet>',
 'xl/worksheets/_rels/sheet1.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+links.map((l,i)=>'<Relationship Id="rId'+(i+1)+'" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="'+xml(l.url)+'" TargetMode="External"/>').join('')+'</Relationships>'})}
 return {workbook,xlsx(leads,filename){const url=URL.createObjectURL(workbook(leads)),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}};
})();
