import fs from 'node:fs';
import assert from 'node:assert/strict';
const wrapper=fs.readFileSync(new URL('../extension/background-wrapper.js',import.meta.url),'utf8');
const fix=fs.readFileSync(new URL('../extension/contact-extraction-fix.js',import.meta.url),'utf8');
const maps=fs.readFileSync(new URL('../extension/maps-page-overrides.js',import.meta.url),'utf8');
const enrichment=fs.readFileSync(new URL('../extension/contact-enrichment.js',import.meta.url),'utf8');
const manifest=JSON.parse(fs.readFileSync(new URL('../extension/manifest.json',import.meta.url),'utf8'));
assert.match(wrapper,/contact-enrichment\.js/);
assert.match(wrapper,/state\.enrichWebsites = true/);
assert.match(fix,/enrichLeadInBackground\(lead, workerRunId\)/);
assert.match(fix,/MHPAccess\.consume\(preview\.usageRequestId\)/);
assert.match(maps,/const root = document\.querySelector\("div\[role='main'\]"\) \|\| document\.body/);
assert.match(enrichment,/MHP_SITE_PAGE_LIMIT = 12/);
assert.match(enrichment,/MHP_CONTACT_CONCURRENCY = 5/);
assert.match(enrichment,/origin\+'\/contact'/);
assert.match(enrichment,/origin\+'\/contact-us'/);
assert.match(enrichment,/data-cfemail/);
assert.match(enrichment,/mhpMergeLeadContactResults/);
assert.match(enrichment,/pendingEnrichment\.add\(task\)/);
assert.deepEqual(new Set(manifest.host_permissions),new Set(['http://*/*','https://*/*']));
console.log('Stable Maps + website contact extraction regression checks passed');
