import playwright from '/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.js';
import assert from 'node:assert/strict';
const {chromium}=playwright;
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844}});
await page.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;let data={ok:true};if(path==='/api/plans')data={ok:true,plans:[{id:'monthly',price:20},{id:'annual',price:100}]};else if(path==='/api/auth/register')data={ok:true,token:'user-token',user:{id:1,email:'buyer@example.test',name:'Buyer'}};else if(path==='/api/account/me')data={ok:true,user:{id:1,email:'buyer@example.test',name:'Buyer'},subscription:null,license:null};else if(path==='/api/activation/request')data={ok:true,requestRef:'ACT-TEST',paymentRef:'PAY-TEST',amount:20,whatsappUrl:'https://wa.me/218931650822?text=test'};else if(path==='/api/admin/login')data={ok:true,token:'admin-session'};else if(path==='/api/admin/summary')data={ok:true,summary:{activeUsers:1,monthlyRevenue:20,activeLicenses:1,expiringSoon:0,leadsToday:4,activeSubscriptions:1,pendingPayments:1,activeAffiliates:0}};else if(path.startsWith('/api/admin/')){const name=path.split('/').pop().replace('-','');data={ok:true,[name]:[],settings:[]}}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)})});
await page.goto('http://127.0.0.1:4173/dist/landing.html?utm_source=test&ref=AF-TEST');
assert.equal(await page.locator('[data-account]').textContent(),'My account');
await page.locator('[data-lang="ar"]').click();
assert.equal(await page.locator('html').getAttribute('dir'),'rtl');
await page.locator('[data-mhp-plan="monthly"]').click();
await page.locator('input[name="name"]').fill('Buyer');
await page.locator('input[name="email"]').fill('buyer@example.test');
await page.locator('input[name="password"]').fill('password1');
await page.locator('#authForm button').click();
await page.locator('#requestActivation').click();
await page.waitForSelector('text=ACT-TEST');
assert.match(await page.locator('#activationResult').textContent(),/ACT-TEST/);
await page.goto('http://127.0.0.1:4173/dist/admin.html');
await page.locator('#adminTokenInput').fill('test-password');
await page.locator('#loginBtn').click();
await page.waitForSelector('#loginGate',{state:'hidden'});
assert.equal(await page.locator('#sActiveUsers').textContent(),'1');
await browser.close();
console.log('Landing mobile, Arabic, account activation, and admin login tests passed');
