const HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-headers':'content-type,authorization,x-admin-token','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'};
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:HEADERS});
const fail=(code,status=400)=>{const e=new Error(code);e.status=status;throw e};
const enc=new TextEncoder();
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const random=n=>b64(crypto.getRandomValues(new Uint8Array(n)));
const hash=async v=>b64(await crypto.subtle.digest('SHA-256',enc.encode(v)));
const email=v=>String(v||'').trim().toLowerCase();
const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)&&v.length<=254;
const sql=(e,q,...p)=>e.DB.prepare(q).bind(...p);
const first=(e,q,...p)=>sql(e,q,...p).first();
const rows=async(e,q,...p)=>(await sql(e,q,...p).all()).results||[];
const run=(e,q,...p)=>sql(e,q,...p).run();
const key=prefix=>prefix+'-'+crypto.randomUUID().replace(/-/g,'').toUpperCase();
async function body(r){if(Number(r.headers.get('content-length')||0)>16384)fail('REQUEST_TOO_LARGE',413);const t=await r.text();if(t.length>16384)fail('REQUEST_TOO_LARGE',413);try{const x=JSON.parse(t||'{}');if(!x||typeof x!=='object'||Array.isArray(x))fail('INVALID_JSON');return x}catch{fail('INVALID_JSON')}}
async function passwordHash(password,salt){const k=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return b64(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations:150000},k,256))}
async function ensureAuthSchema(e){await e.DB.batch([sql(e,'CREATE TABLE IF NOT EXISTS auth_credentials(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'),sql(e,'CREATE TABLE IF NOT EXISTS auth_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'),sql(e,'CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id,expires_at)'),sql(e,'CREATE TABLE IF NOT EXISTS admin_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)')]);try{await run(e,'INSERT OR IGNORE INTO auth_credentials(user_id,password_hash,password_salt) SELECT id,password_hash,password_salt FROM users WHERE password_hash IS NOT NULL AND password_salt IS NOT NULL')}catch{}}
async function settings(e){const z=Object.fromEntries((await rows(e,'SELECT key,value FROM settings')).map(x=>[x.key,x.value]));const numeric=['monthly_price_usd','annual_price_usd','monthly_daily_limit','allowed_devices','affiliate_first_purchase_percent','affiliate_renewal_percent'];const out={monthly_price_usd:20,annual_price_usd:100,monthly_daily_limit:1500,allowed_devices:2,affiliate_first_purchase_percent:50,affiliate_renewal_percent:20};for(const k of numeric)if(z[k]!=null&&Number.isFinite(Number(z[k])))out[k]=Number(z[k]);return out}
const plan=(s,id)=>{if(!['monthly','annual'].includes(id))fail('INVALID_PLAN');return {id,price:s[id+'_price_usd'],dailyLeadLimit:id==='monthly'?s.monthly_daily_limit:null,durationDays:id==='monthly'?30:365}};
async function session(r,e,admin=false){const a=r.headers.get('authorization')||'';if(!a.startsWith('Bearer '))fail('UNAUTHORIZED',401);const h=await hash(a.slice(7));const u=admin?await first(e,"SELECT id FROM admin_sessions WHERE token_hash=? AND julianday(expires_at)>julianday('now')",h):await first(e,"SELECT u.id,u.email,u.name,u.status FROM auth_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND julianday(s.expires_at)>julianday('now') AND u.status='active'",h);if(!u)fail('UNAUTHORIZED',401);return u}
async function rateLimit(r,e,path){const ip=r.headers.get('cf-connecting-ip')||'unknown';const h=await hash(path+'|'+ip+'|'+Math.floor(Date.now()/600000));const q=await first(e,"INSERT INTO request_limits(key,count,expires_at) VALUES(?,1,datetime('now','+20 minutes')) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count",h);if(q.count>40)fail('TOO_MANY_REQUESTS',429)}
async function audit(e,event,actor,targetType,targetId,metadata=null,result='success'){await run(e,'INSERT INTO audit_logs(event_type,actor_type,actor,target_type,target_id,result,metadata_json) VALUES(?,?,?,?,?,?,?)',event,'admin',String(actor||'admin'),targetType||null,String(targetId||''),result,metadata?JSON.stringify(metadata):null)}
async function grant(e,type,source,userId,planId){const existing=await first(e,'SELECT g.*,l.license_key,s.expires_at FROM entitlement_grants g JOIN licenses l ON l.id=g.license_id JOIN subscriptions s ON s.id=g.subscription_id WHERE source_type=? AND source_ref=?',type,source);if(existing){if(existing.user_id!==userId)fail('CODE_ALREADY_USED',409);return {already:true,licenseKey:existing.license_key,expiresAt:existing.expires_at}}if(planId==='monthly'&&await first(e,"SELECT id FROM subscriptions WHERE user_id=? AND plan_id='annual' AND status='active' AND julianday(expires_at)>julianday('now')",userId))fail('ANNUAL_DOWNGRADE_NOT_ALLOWED',409);const s=await settings(e),p=plan(s,planId);try{await run(e,'INSERT INTO entitlement_grants(source_type,source_ref,user_id,plan_id,license_key,device_limit,daily_limit) VALUES(?,?,?,?,?,?,?)',type,source,userId,planId,key('MHP'),s.allowed_devices,p.dailyLeadLimit)}catch(err){const won=await first(e,'SELECT user_id FROM entitlement_grants WHERE source_type=? AND source_ref=?',type,source);if(!won||won.user_id!==userId)throw err;}const g=await first(e,'SELECT l.license_key,s.expires_at FROM entitlement_grants g JOIN licenses l ON l.id=g.license_id JOIN subscriptions s ON s.id=g.subscription_id WHERE source_type=? AND source_ref=?',type,source);return {licenseKey:g.license_key,expiresAt:g.expires_at}}
async function license(r,e,x){const k=String(x.licenseKey||'').trim().toUpperCase(),device=String(x.deviceId||'').trim();if(!k||!device||device.length>128)fail('LICENSE_AND_DEVICE_REQUIRED');const l=await first(e,"SELECT l.*,s.plan_id,s.daily_lead_limit,u.email FROM licenses l JOIN subscriptions s ON s.id=l.subscription_id JOIN users u ON u.id=l.user_id WHERE l.license_key=? AND l.status='active' AND s.status='active' AND u.status='active' AND julianday(l.expires_at)>julianday('now') AND julianday(s.expires_at)>julianday('now')",k);if(!l)fail('INVALID_LICENSE',401);if(x.email&&email(x.email)!==email(l.email))fail('LICENSE_EMAIL_MISMATCH',403);let d=await first(e,'SELECT id,status FROM devices WHERE license_id=? AND device_uid=?',l.id,device);if(d?.status==='blocked')fail('DEVICE_BLOCKED',403);if(!d){try{await run(e,"INSERT INTO devices(user_id,license_id,device_uid,os,browser,last_ip,status) VALUES(?,?,?,?,?,?,'trusted')",l.user_id,l.id,device,String(x.os||'').slice(0,100),String(x.browser||'').slice(0,100),r.headers.get('cf-connecting-ip'))}catch(err){d=await first(e,'SELECT status FROM devices WHERE license_id=? AND device_uid=?',l.id,device);if(!d)fail('DEVICE_LIMIT_REACHED',403);if(d.status==='blocked')fail('DEVICE_BLOCKED',403)}}return l}
async function activation(r,e,x,u){const s=await settings(e),p=plan(s,x.planId);const ref=String(x.referralCode||'').trim().toUpperCase();if(ref&&!await first(e,"SELECT id FROM payments WHERE user_id=? AND status='confirmed'",u.id)){await run(e,"INSERT OR IGNORE INTO referrals(affiliate_id,referred_user_id) SELECT id,? FROM affiliates WHERE referral_code=? AND status='active' AND lower(email)!=?",u.id,ref,u.email)}let old=await first(e,"SELECT a.request_ref,a.payment_ref,a.plan_id,p.amount_cents FROM activation_requests a JOIN payments p ON p.payment_ref=a.payment_ref WHERE a.user_id=? AND a.plan_id=? AND a.status='pending' AND p.status='pending' ORDER BY a.id DESC LIMIT 1",u.id,p.id);if(!old){await e.DB.batch([sql(e,"UPDATE activation_requests SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND status='pending'",u.id),sql(e,"UPDATE payments SET status='rejected' WHERE user_id=? AND status='pending' AND payment_ref IN (SELECT payment_ref FROM activation_requests WHERE user_id=?)",u.id,u.id)]);const ar=key('ACT'),pay=key('PAY');await e.DB.batch([sql(e,"INSERT INTO payments(payment_ref,user_id,method,amount_cents,payment_type,status) VALUES(?,?,'MANUAL_WHATSAPP',?,'first_purchase','pending')",pay,u.id,Math.round(p.price*100)),sql(e,"INSERT INTO activation_requests(request_ref,user_id,plan_id,payment_ref) VALUES(?,?,?,?)",ar,u.id,p.id,pay)]);old={request_ref:ar,payment_ref:pay,plan_id:p.id,amount_cents:Math.round(p.price*100)}}const msg=['مرحبًا، أريد تفعيل Maps Hunter Pro.','رقم الطلب: '+old.request_ref,'البريد: '+u.email,'الخطة: '+old.plan_id,'السعر: $'+(old.amount_cents/100)].join('\n');return json({ok:true,requestRef:old.request_ref,paymentRef:old.payment_ref,planId:old.plan_id,amount:old.amount_cents/100,whatsappUrl:'https://wa.me/218931650822?text='+encodeURIComponent(msg)},201)}
async function dispatch(r,e){const url=new URL(r.url),p=url.pathname,m=r.method;if(m==='OPTIONS')return new Response(null,{status:204,headers:HEADERS});if(p==='/api/health'){await ensureAuthSchema(e);return json({ok:true,version:'5.2.0-auth-repair',database:(await first(e,'SELECT 1 ok')).ok===1?'connected':'error',authentication:(await first(e,"SELECT name FROM sqlite_master WHERE type='table' AND name='auth_credentials'"))?'ready':'error'})}if(p==='/api/plans') {const s=await settings(e);return json({ok:true,plans:['monthly','annual'].map(id=>plan(s,id)),affiliate:{firstPurchasePercent:s.affiliate_first_purchase_percent,renewalPercent:s.affiliate_renewal_percent}})}
if(['/api/auth/register','/api/auth/login','/api/admin/login','/api/codes/redeem'].includes(p)&&m==='POST')await rateLimit(r,e,p);
if(p==='/api/admin/login'&&m==='POST'){await ensureAuthSchema(e);const x=await body(r);if(!e.ADMIN_TOKEN||x.username!==(e.ADMIN_USERNAME||'anasbm')||await hash(String(x.password||''))!==await hash(e.ADMIN_TOKEN))fail('INVALID_ADMIN_CREDENTIALS',401);const t=random(32);await run(e,"INSERT INTO admin_sessions(token_hash,expires_at) VALUES(?,datetime('now','+4 hours'))",await hash(t));await audit(e,'ADMIN_LOGIN',x.username,'session','created',{ip:r.headers.get('cf-connecting-ip')});return json({ok:true,token:t})}
if(['/api/auth/login','/api/auth/register'].includes(p)&&m==='POST'){await ensureAuthSchema(e);const x=await body(r),em=email(x.email),pw=String(x.password||'');if(!validEmail(em)||pw.length<8||pw.length>256)fail('INVALID_INPUT');let u=await first(e,'SELECT id,email,name,status FROM users WHERE email=?',em),credential=u?await first(e,'SELECT password_hash,password_salt FROM auth_credentials WHERE user_id=?',u.id):null;if(p.endsWith('/register')){if(u)fail('ACCOUNT_EXISTS',409);const name=String(x.name||'').trim().slice(0,120);if(!name)fail('NAME_REQUIRED');try{await run(e,'INSERT INTO users(email,name,locale) VALUES(?,?,?)',em,name,['en','ar','ru','de','es'].includes(x.locale)?x.locale:'en')}catch(err){if(await first(e,'SELECT id FROM users WHERE email=?',em))fail('ACCOUNT_EXISTS',409);throw err}u=await first(e,'SELECT id,email,name,status FROM users WHERE email=?',em);const salt=random(16);await run(e,'INSERT INTO auth_credentials(user_id,password_hash,password_salt) VALUES(?,?,?)',u.id,await passwordHash(pw,salt),salt);await run(e,'INSERT OR IGNORE INTO acquisition(user_id,source,campaign) VALUES(?,?,?)',u.id,String(x.source||'direct').slice(0,120),String(x.campaign||'').slice(0,120))}else if(!u||u.status!=='active'||!credential||await passwordHash(pw,credential.password_salt)!==credential.password_hash)fail('INVALID_CREDENTIALS',401);const t=random(32);await run(e,"INSERT INTO auth_sessions(user_id,token_hash,expires_at) VALUES(?,?,datetime('now','+30 days'))",u.id,await hash(t));return json({ok:true,token:t,user:{id:u.id,email:u.email,name:u.name}},p.endsWith('/register')?201:200)}
if(p==='/api/auth/logout'&&m==='POST'){const a=(r.headers.get('authorization')||'').replace(/^Bearer /,'');await run(e,'DELETE FROM auth_sessions WHERE token_hash=?',await hash(a));return json({ok:true})}
if(p==='/api/account/me'&&m==='GET'){const u=await session(r,e);return json({ok:true,user:u,subscription:await first(e,'SELECT * FROM subscriptions WHERE user_id=? ORDER BY id DESC LIMIT 1',u.id),license:await first(e,'SELECT license_key,status,device_limit,expires_at FROM licenses WHERE user_id=? ORDER BY id DESC LIMIT 1',u.id)})}
if(p==='/api/activation/request'&&m==='POST')return activation(r,e,await body(r),await session(r,e));
if(p==='/api/codes/redeem'&&m==='POST'){const u=await session(r,e),x=await body(r),c=String(x.code||'').trim().toUpperCase();const z=await first(e,'SELECT * FROM activation_codes WHERE code=?',c);if(!z)fail('CODE_NOT_FOUND',404);if(z.status==='redeemed')fail('CODE_ALREADY_USED',409);if(z.status!=='unused')fail('CODE_NOT_AVAILABLE',409);if(z.expires_at&&Date.parse(z.expires_at)<=Date.now())fail('CODE_EXPIRED',410);return json({ok:true,planId:z.plan_id,...await grant(e,'code',c,u.id,z.plan_id)})}
if(['/api/license/validate','/api/usage/consume'].includes(p)&&m==='POST'){const x=await body(r),l=await license(r,e,x);if(p.endsWith('/consume')){const id=String(x.requestId||''),amount=Number(x.amount||1);if(id.length<8||id.length>128||!Number.isInteger(amount)||amount<1||amount>100)fail('INVALID_USAGE');const prior=await first(e,'SELECT user_id,license_id,amount FROM usage_events WHERE request_id=?',id);if(prior&&(prior.user_id!==l.user_id||prior.license_id!==l.id||prior.amount!==amount))fail('REQUEST_ID_CONFLICT',409);if(!prior)await run(e,'INSERT INTO usage_events(request_id,user_id,license_id,usage_date,amount) VALUES(?,?,?,date(\'now\'),?)',id,l.user_id,l.id,amount)}const used=await first(e,"SELECT leads_processed FROM usage_daily WHERE user_id=? AND usage_date=date('now')",l.user_id);return json({ok:true,valid:true,license:{key:l.license_key,planId:l.plan_id,dailyLeadLimit:l.daily_lead_limit,deviceLimit:l.device_limit,expiresAt:l.expires_at,email:l.email},usedToday:used?.leads_processed||0})}
if(p==='/api/affiliate/register'&&m==='POST'){const u=await session(r,e),s=await settings(e);await run(e,"INSERT OR IGNORE INTO affiliates(email,name,referral_code,status,first_purchase_percent,renewal_percent) VALUES(?,?,?,'active',?,?)",u.email,u.name,key('AF'),s.affiliate_first_purchase_percent,s.affiliate_renewal_percent);return json({ok:true,affiliate:await first(e,'SELECT referral_code,status,first_purchase_percent,renewal_percent FROM affiliates WHERE email=?',u.email)})}
if(p==='/api/affiliate/me'&&m==='GET'){const u=await session(r,e),a=await first(e,"SELECT * FROM affiliates WHERE email=? AND status='active'",u.email);if(!a)fail('AFFILIATE_NOT_FOUND',404);const stats=await first(e,"SELECT (SELECT count(*) FROM referrals WHERE affiliate_id=?) referrals,(SELECT count(*) FROM referrals WHERE affiliate_id=? AND converted_at IS NOT NULL) conversions,(SELECT coalesce(sum(amount_cents),0) FROM commissions WHERE affiliate_id=? AND status IN ('approved','paid')) earned_cents,(SELECT coalesce(sum(c.amount_cents),0) FROM commissions c LEFT JOIN payout_commissions pc ON pc.commission_id=c.id WHERE c.affiliate_id=? AND c.status='approved' AND pc.commission_id IS NULL) available_cents",a.id,a.id,a.id,a.id);return json({ok:true,affiliate:{referralCode:a.referral_code,firstPurchasePercent:a.first_purchase_percent,renewalPercent:a.renewal_percent},stats,payouts:await rows(e,'SELECT payout_ref,amount_cents,method,destination,status,created_at,processed_at FROM payouts WHERE affiliate_id=? ORDER BY id DESC LIMIT 50',a.id)})}
if(p==='/api/affiliate/payouts'&&m==='POST'){const u=await session(r,e),x=await body(r),a=await first(e,"SELECT id FROM affiliates WHERE email=? AND status='active'",u.email);if(!a)fail('AFFILIATE_NOT_FOUND',404);if(!['USDT','REDOTPAY'].includes(x.method)||String(x.destination||'').trim().length<4)fail('INVALID_PAYOUT');const cs=await rows(e,"SELECT c.id,c.amount_cents FROM commissions c LEFT JOIN payout_commissions pc ON pc.commission_id=c.id WHERE c.affiliate_id=? AND c.status='approved' AND pc.commission_id IS NULL ORDER BY c.id",a.id);const amount=cs.reduce((n,c)=>n+Number(c.amount_cents),0);if(amount<=0)fail('NO_AVAILABLE_BALANCE',409);const ref=key('PO');await e.DB.batch([sql(e,"INSERT INTO payouts(payout_ref,affiliate_id,amount_cents,method,destination,status) VALUES(?,?,?,?,?,'pending')",ref,a.id,amount,x.method,String(x.destination).trim().slice(0,200)),...cs.map(c=>sql(e,'INSERT INTO payout_commissions(payout_id,commission_id,amount_cents) SELECT id,?,? FROM payouts WHERE payout_ref=?',c.id,c.amount_cents,ref))]);return json({ok:true,payoutRef:ref,amountCents:amount},201)}
if(p==='/api/account/data-request'&&m==='POST'){const u=await session(r,e),x=await body(r);if(!['access','correction','deletion'].includes(x.type))fail('INVALID_REQUEST_TYPE');const ref=key('DR');await run(e,'INSERT INTO data_requests(request_ref,user_id,request_type,note) VALUES(?,?,?,?)',ref,u.id,x.type,String(x.note||'').slice(0,1000));return json({ok:true,requestRef:ref,status:'pending'},201)}
if(p.startsWith('/api/admin/')){await session(r,e,true);return admin(r,e,url)}fail('NOT_FOUND',404)}
async function admin(r,e,url){const p=url.pathname,m=r.method;const limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit'))||50)),offset=Math.max(0,Number(url.searchParams.get('offset'))||0),q='%'+String(url.searchParams.get('q')||'').slice(0,120)+'%';
if(p==='/api/admin/logout'&&m==='POST'){await audit(e,'ADMIN_LOGOUT','admin','session','current');await run(e,'DELETE FROM admin_sessions WHERE token_hash=?',await hash((r.headers.get('authorization')||'').slice(7)));return json({ok:true})}
if(p==='/api/admin/summary'){const count=async(q)=>Number((await first(e,q)).c||0);const active="status='active' AND julianday(expires_at)>julianday('now')";const s={users:await count('SELECT count(*) c FROM users'),activeUsers:await count("SELECT count(*) c FROM users WHERE status='active'"),pendingActivations:await count("SELECT count(*) c FROM activation_requests WHERE status='pending'"),activeSubscriptions:await count('SELECT count(*) c FROM subscriptions WHERE '+active),activeLicenses:await count('SELECT count(*) c FROM licenses WHERE '+active),unusedCodes:await count("SELECT count(*) c FROM activation_codes WHERE status='unused' AND (expires_at IS NULL OR julianday(expires_at)>julianday('now'))"),monthlyRevenue:await count("SELECT coalesce(sum(amount_cents),0) c FROM payments WHERE status='confirmed' AND strftime('%Y-%m',confirmed_at)=strftime('%Y-%m','now')")/100,leadsToday:await count("SELECT coalesce(sum(leads_processed),0) c FROM usage_daily WHERE usage_date=date('now')"),pendingPayments:await count("SELECT count(*) c FROM payments WHERE status='pending'"),activeAffiliates:await count("SELECT count(*) c FROM affiliates WHERE status='active'"),expiringSoon:await count("SELECT count(*) c FROM subscriptions WHERE status='active' AND julianday(expires_at)>julianday('now') AND julianday(expires_at)<=julianday('now','+3 days')")};return json({ok:true,summary:s})}
if(p==='/api/admin/settings'){if(m==='PATCH'){const x=await body(r),ranges={monthly_price_usd:[1,10000],annual_price_usd:[1,100000],monthly_daily_limit:[1,1000000],allowed_devices:[1,10],affiliate_first_purchase_percent:[0,100],affiliate_renewal_percent:[0,100]};const ops=[],changed=[];for(const [k,v]of Object.entries(x)){if(!(k in ranges))continue;const n=Number(v),[lo,hi]=ranges[k];if(!Number.isFinite(n)||n<lo||n>hi||(!k.includes('price')&&!Number.isInteger(n)))fail('INVALID_SETTING');changed.push(k);ops.push(sql(e,'INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP',k,String(n)))}if(ops.length){await e.DB.batch(ops);await audit(e,'SETTINGS_UPDATED','admin','settings','commercial',{keys:changed})}}return json({ok:true,settings:await rows(e,'SELECT key,value FROM settings')})}
if(p==='/api/admin/codes/generate'&&m==='POST'){const x=await body(r),s=await settings(e);plan(s,x.planId);const n=Number(x.quantity||1);if(!Number.isInteger(n)||n<1||n>100)fail('INVALID_QUANTITY');let exp=null;if(x.expiresAt){if(!Number.isFinite(Date.parse(x.expiresAt))||Date.parse(x.expiresAt)<=Date.now())fail('INVALID_EXPIRY');exp=new Date(x.expiresAt).toISOString()}const codes=Array.from({length:n},()=>key('MHP-'+(x.planId==='annual'?'Y':'M')));await e.DB.batch(codes.map(c=>sql(e,'INSERT INTO activation_codes(code,plan_id,note,purchaser_email,expires_at) VALUES(?,?,?,?,?)',c,x.planId,String(x.note||'').slice(0,500)||null,email(x.purchaserEmail)||null,exp)));return json({ok:true,codes,planId:x.planId},201)}
if(p==='/api/admin/licenses'&&m==='POST'){const x=await body(r),s=await settings(e),p0=plan(s,x.planId),em=email(x.email),u=await first(e,'SELECT id,email FROM users WHERE email=? AND status=\'active\'',em);if(!u)fail('CUSTOMER_ACCOUNT_REQUIRED',409);const source=key('MHP-A');await run(e,'INSERT INTO activation_codes(code,plan_id,note,purchaser_email) VALUES(?,?,?,?)',source,p0.id,'Direct admin activation',em);const result=await grant(e,'code',source,u.id,p0.id);const deviceLimit=Math.min(10,Math.max(1,Number(x.deviceLimit)||s.allowed_devices));await run(e,'UPDATE licenses SET device_limit=? WHERE license_key=?',deviceLimit,result.licenseKey);return json({ok:true,license:{licenseKey:result.licenseKey,email:em,planId:p0.id,expiresAt:result.expiresAt,deviceLimit}},201)}
let a=p.match(/^\/api\/admin\/activation-requests\/([^/]+)\/activate$/);if(a&&m==='POST'){const z=await first(e,'SELECT * FROM activation_requests WHERE request_ref=?',decodeURIComponent(a[1]));if(!z)fail('NOT_FOUND',404);if(z.status==='approved')return json({ok:true,already:true});return json({ok:true,...await grant(e,'payment',z.payment_ref,z.user_id,z.plan_id)})}
a=p.match(/^\/api\/admin\/payments\/([^/]+)\/confirm$/);if(a&&m==='POST'){const ref=decodeURIComponent(a[1]),x=await body(r),z=await first(e,'SELECT * FROM activation_requests WHERE payment_ref=?',ref);if(!z)fail('ACTIVATION_REQUEST_REQUIRED',409);if(z.status==='approved')return json({ok:true,already:true});const external=String(x.externalReference||'').trim().slice(0,200);if(external){const duplicate=await first(e,"SELECT payment_ref FROM payments WHERE external_reference=? AND payment_ref!=?",external,ref);if(duplicate)fail('DUPLICATE_EXTERNAL_REFERENCE',409);await run(e,'UPDATE payments SET external_reference=? WHERE payment_ref=? AND status=\'pending\'',external,ref)}const result=await grant(e,'payment',z.payment_ref,z.user_id,z.plan_id);await audit(e,'PAYMENT_CONFIRMED','admin','payment',ref,{externalReference:external||null});return json({ok:true,...result})}
a=p.match(/^\/api\/admin\/payments\/([^/]+)\/refund$/);if(a&&m==='POST'){const ref=decodeURIComponent(a[1]),p0=await first(e,"SELECT * FROM payments WHERE payment_ref=? AND status='confirmed'",ref);if(!p0)fail('PAYMENT_NOT_CONFIRMED',409);await e.DB.batch([sql(e,"UPDATE payments SET status='refunded' WHERE id=? AND status='confirmed'",p0.id),sql(e,"UPDATE commissions SET status='cancelled' WHERE payment_id=? AND status!='paid'",p0.id),sql(e,"UPDATE licenses SET status='revoked',updated_at=CURRENT_TIMESTAMP WHERE subscription_id=?",p0.subscription_id),sql(e,"UPDATE subscriptions SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=?",p0.subscription_id)]);await audit(e,'PAYMENT_REFUNDED','admin','payment',ref,{amountCents:p0.amount_cents});return json({ok:true})}
a=p.match(/^\/api\/admin\/codes\/([^/]+)\/revoke$/);if(a&&m==='POST'){const id=decodeURIComponent(a[1]),z=await run(e,"UPDATE activation_codes SET status='revoked' WHERE code=? AND status='unused'",id);await audit(e,'CODE_REVOKED','admin','code',id);return json({ok:true,changed:z.meta.changes})}
a=p.match(/^\/api\/admin\/licenses\/([^/]+)\/revoke$/);if(a&&m==='POST'){const id=decodeURIComponent(a[1]),z=await run(e,"UPDATE licenses SET status='revoked',updated_at=CURRENT_TIMESTAMP WHERE license_key=?",id);await audit(e,'LICENSE_REVOKED','admin','license',id);return json({ok:true,changed:z.meta.changes})}
a=p.match(/^\/api\/admin\/devices\/(\d+)\/(block|unblock|release)$/);if(a&&m==='POST'){const id=Number(a[1]),action=a[2];if(action==='release')await run(e,'DELETE FROM devices WHERE id=?',id);else await run(e,'UPDATE devices SET status=? WHERE id=?',action==='block'?'blocked':'trusted',id);await audit(e,'DEVICE_'+action.toUpperCase(),'admin','device',id);return json({ok:true})}
a=p.match(/^\/api\/admin\/payouts\/([^/]+)\/(approve|pay|reject)$/);if(a&&m==='POST'){const ref=decodeURIComponent(a[1]),action=a[2],status=action==='pay'?'paid':action==='approve'?'approved':'rejected';const z=await first(e,'SELECT id,status FROM payouts WHERE payout_ref=?',ref);if(!z)fail('NOT_FOUND',404);if(z.status===status)return json({ok:true,already:true});if((status==='approved'&&z.status!=='pending')||(status==='paid'&&z.status!=='approved')||(status==='rejected'&&!['pending','approved'].includes(z.status)))fail('INVALID_PAYOUT_TRANSITION',409);await e.DB.batch([sql(e,'UPDATE payouts SET status=?,processed_at=CASE WHEN ? IN (\'paid\',\'rejected\') THEN CURRENT_TIMESTAMP ELSE processed_at END WHERE id=?',status,status,z.id),sql(e,"UPDATE commissions SET status=CASE WHEN ?='paid' THEN 'paid' WHEN ?='rejected' THEN 'approved' ELSE status END,paid_at=CASE WHEN ?='paid' THEN CURRENT_TIMESTAMP ELSE paid_at END WHERE id IN (SELECT commission_id FROM payout_commissions WHERE payout_id=?)",status,status,status,z.id)]);await audit(e,'PAYOUT_'+status.toUpperCase(),'admin','payout',ref);return json({ok:true,status})}
a=p.match(/^\/api\/admin\/data-requests\/([^/]+)\/complete$/);if(a&&m==='POST'){const ref=decodeURIComponent(a[1]),z=await first(e,"SELECT * FROM data_requests WHERE request_ref=? AND status IN ('pending','verified')",ref);if(!z)fail('REQUEST_NOT_PENDING',409);if(z.request_type==='deletion'){await e.DB.batch([sql(e,'DELETE FROM auth_sessions WHERE user_id=?',z.user_id),sql(e,'DELETE FROM auth_credentials WHERE user_id=?',z.user_id),sql(e,'DELETE FROM devices WHERE user_id=?',z.user_id),sql(e,'DELETE FROM acquisition WHERE user_id=?',z.user_id),sql(e,"UPDATE users SET email='deleted+'||id||'@privacy.invalid',name='Deleted user',status='inactive',updated_at=CURRENT_TIMESTAMP WHERE id=?",z.user_id)]);}await run(e,"UPDATE data_requests SET status='completed',completed_at=CURRENT_TIMESTAMP WHERE id=?",z.id);await audit(e,'DATA_REQUEST_COMPLETED','admin','data_request',ref,{type:z.request_type,userId:z.user_id});return json({ok:true})}
const lists={
users:['users',"SELECT u.id,u.email,u.name,u.status,u.created_at,s.plan_id,s.status subscription_status,s.expires_at,(SELECT count(*) FROM devices d WHERE d.user_id=u.id) devices FROM users u LEFT JOIN subscriptions s ON s.id=(SELECT id FROM subscriptions WHERE user_id=u.id ORDER BY id DESC LIMIT 1) WHERE u.email LIKE ? ORDER BY u.id DESC"],
'activation-requests':['requests','SELECT ar.*,u.email,u.name FROM activation_requests ar JOIN users u ON u.id=ar.user_id WHERE u.email LIKE ? OR ar.request_ref LIKE ? ORDER BY ar.id DESC'],
subscriptions:['subscriptions','SELECT s.*,u.email FROM subscriptions s JOIN users u ON u.id=s.user_id WHERE u.email LIKE ? ORDER BY s.id DESC'],
licenses:['licenses','SELECT l.*,u.email,s.plan_id FROM licenses l JOIN users u ON u.id=l.user_id LEFT JOIN subscriptions s ON s.id=l.subscription_id WHERE u.email LIKE ? OR l.license_key LIKE ? ORDER BY l.id DESC'],
codes:['codes','SELECT ac.*,u.email redeemed_by_email FROM activation_codes ac LEFT JOIN users u ON u.id=ac.redeemed_by_user_id WHERE ac.code LIKE ? OR coalesce(u.email,\'\') LIKE ? ORDER BY ac.id DESC'],
devices:['devices','SELECT d.*,u.email,l.license_key FROM devices d JOIN users u ON u.id=d.user_id JOIN licenses l ON l.id=d.license_id WHERE u.email LIKE ? ORDER BY d.id DESC'],
payments:['payments','SELECT p.*,u.email FROM payments p JOIN users u ON u.id=p.user_id WHERE u.email LIKE ? OR p.payment_ref LIKE ? ORDER BY p.id DESC'],
affiliates:['affiliates',"SELECT a.*,(SELECT count(*) FROM referrals r WHERE r.affiliate_id=a.id) referrals,(SELECT coalesce(sum(amount_cents),0) FROM commissions c WHERE c.affiliate_id=a.id AND status IN ('approved','paid')) commission_cents FROM affiliates a WHERE a.email LIKE ? ORDER BY a.id DESC"],
payouts:['payouts','SELECT p.*,a.email FROM payouts p JOIN affiliates a ON a.id=p.affiliate_id WHERE a.email LIKE ? ORDER BY p.id DESC'],
usage:['usage','SELECT d.*,u.email FROM usage_daily d JOIN users u ON u.id=d.user_id WHERE u.email LIKE ? ORDER BY d.usage_date DESC'],
logs:['logs',"SELECT * FROM audit_logs WHERE coalesce(actor,'') LIKE ? ORDER BY id DESC"],
'data-requests':['requests',"SELECT d.*,u.email FROM data_requests d JOIN users u ON u.id=d.user_id WHERE u.email LIKE ? OR d.request_ref LIKE ? ORDER BY d.id DESC"]};
const spec=lists[p.split('/').pop()];if(spec&&m==='GET'){const [name,query]=spec,args=Array((query.match(/\?/g)||[]).length).fill(q),data=await rows(e,query+' LIMIT ? OFFSET ?',...args,limit+1,offset);return json({ok:true,[name]:data.slice(0,limit),hasMore:data.length>limit,offset,limit})}fail('NOT_FOUND',404)}
async function maintenance(e){const results=await e.DB.batch([sql(e,"DELETE FROM auth_sessions WHERE julianday(expires_at)<=julianday('now')"),sql(e,"DELETE FROM admin_sessions WHERE julianday(expires_at)<=julianday('now')"),sql(e,"DELETE FROM request_limits WHERE julianday(expires_at)<=julianday('now')"),sql(e,"DELETE FROM usage_events WHERE julianday(created_at)<=julianday('now','-90 days')"),sql(e,"UPDATE devices SET last_ip=NULL WHERE last_ip IS NOT NULL AND julianday(last_seen_at)<=julianday('now','-30 days')")]);const changed=results.reduce((n,x)=>n+Number(x.meta?.changes||0),0);await run(e,"INSERT INTO maintenance_runs(run_type,rows_changed) VALUES('retention',?)",changed);return changed}
export default {async fetch(r,e){try{return await dispatch(r,e)}catch(err){const message=String(err.message||err);const known=['CODE_NOT_AVAILABLE','PAYMENT_NOT_PENDING','ACCOUNT_INACTIVE','ANNUAL_DOWNGRADE_NOT_ALLOWED','DAILY_LIMIT_REACHED','INVALID_LICENSE','DEVICE_LIMIT_REACHED','DUPLICATE_EXTERNAL_REFERENCE'].find(x=>message.includes(x));return json({ok:false,error:err.status?message:known||'SERVER_ERROR'},err.status||(known?409:500))}},async scheduled(c,e,ctx){ctx.waitUntil(maintenance(e))}};
