const HEADERS={'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-headers':'content-type,authorization,x-admin-token','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'};
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:HEADERS});
const fail=(code,status=400)=>{const e=new Error(code);e.status=status;throw e};
const enc=new TextEncoder();
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const random=n=>b64(crypto.getRandomValues(new Uint8Array(n)));
const hash=async v=>b64(await crypto.subtle.digest('SHA-256',enc.encode(v)));
const email=v=>String(v||'').trim().toLowerCase();
const validEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)&&v.length<=254;
const sql=(e,q,...p)=>e.DB.prepare(q).bind(...p);
const first=(e,q,...p)=>sql(e,q,...p).first();
const rows=async(e,q,...p)=>(await sql(e,q,...p).all()).results||[];
const run=(e,q,...p)=>sql(e,q,...p).run();
const key=prefix=>prefix+'-'+crypto.randomUUID().replace(/-/g,'').toUpperCase();
async function body(r){if(Number(r.headers.get('content-length')||0)>16384)fail('REQUEST_TOO_LARGE',413);const t=await r.text();if(t.length>16384)fail('REQUEST_TOO_LARGE',413);try{const x=JSON.parse(t||'{}');if(!x||typeof x!=='object'||Array.isArray(x))fail('INVALID_JSON');return x}catch{fail('INVALID_JSON')}}
const PASSWORD_ITERATIONS=100000;
async function passwordHash(password,salt,iterations=PASSWORD_ITERATIONS){const k=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return b64(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations},k,256))}
async function ensureAuthSchema(e){await e.DB.batch([sql(e,'CREATE TABLE IF NOT EXISTS auth_credentials(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,iterations INTEGER NOT NULL DEFAULT 150000,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'),sql(e,'CREATE TABLE IF NOT EXISTS auth_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)'),sql(e,'CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id,expires_at)'),sql(e,'CREATE TABLE IF NOT EXISTS admin_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,token_hash TEXT NOT NULL UNIQUE,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)')]);try{await run(e,'ALTER TABLE auth_credentials ADD COLUMN iterations INTEGER NOT NULL DEFAULT 150000')}catch{}try{await run(e,'INSERT OR IGNORE INTO auth_credentials(user_id,password_hash,password_salt,iterations) SELECT id,password_hash,password_salt,150000 FROM users WHERE password_hash IS NOT NULL AND password_salt IS NOT NULL')}catch{}}
async function settings(e){const z=Object.fromEntries((await rows(e,'SELECT key,value FROM settings')).map(x=>[x.key,x.value]));const numeric=['monthly_price_usd','annual_price_usd','monthly_daily_limit','allowed_devices','affiliate_first_purchase_percent','affiliate_renewal_percent'];const out={monthly_price_usd:20,annual_price_usd:100,monthly_daily_limit:1500,allowed_devices:2,affiliate_first_purchase_percent:50,affiliate_renewal_percent:20};for(const k of numeric)if(z[k]!=null&&Number.isFinite(Number(z[k])))out[k]=Number(z[k]);return out}
const plan=(s,id)=>{if(!['monthly','annual'].includes(id))fail('INVALID_PLAN');return {id,price:s[id+'_price_usd'],dailyLeadLimit:id==='monthly'?s.monthly_daily_limit:null,durationDays:id==='monthly'?30:365}};
async function session(r,e,admin=false){const a=r.headers.get('authorization')||'';if(!a.startsWith('Bearer '))fail('UNAUTHORIZED',401);const h=await hash(a.slice(7));const u=admin?await first(e,"SELECT id FROM admin_sessions WHERE token_hash=? AND julianday(expires_at)>julianday('now')",h):await first(e,"SELECT u.id,u.email,u.name,u.status FROM auth_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND julianday(s.expires_at)>julianday('now') AND u.status='active'",h);if(!u)fail('UNAUTHORIZED',401);return u}
async function rateLimit(r,e,path){const ip=r.headers.get('cf-connecting-ip')||'unknown';const h=await hash(path+'|'+ip+'|'+Math.floor(Date.now()/600000));const q=await first(e,"INSERT INTO request_limits(key,count,expires_at) VALUES(?,1,datetime('now','+20 minutes')) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count",h);if(q.count>40)fail('TOO_MANY_REQUESTS',429)}
async function audit(e,event,actor,targetType,targetId,metadata=null,result='success'){await run(e,'INSERT INTO audit_logs(event_type,actor_type,actor,target_type,target_id,result,metadata_json) VALUES(?,?,?,?,?,?,?)',event,'admin',String(actor||'admin'),targetType||null,String(targetId||''),result,metadata?JSON.stringify(metadata):null)}
async function grant(e,type,source,userId,planId){const existing=await first(e,'SELECT g.*,l.license_key,s.expires_at FROM entitlement_grants g JOIN licenses l ON l.id=g.license_id JOIN subscriptions s ON s.id=g.subscription_id WHERE source_type=? AND source_ref=?',type,source);if(existing){if(existing.user_id!==userId)fail('CODE_ALREADY_USED',409);return {already:true,licenseKey:existing.license_key,expiresAt:existing.expires_at}}if(planId==='monthly'&&await first(e,"SELECT id FROM subscriptions WHERE user_id=? AND plan_id='annual' AND status='active' AND julianday(expires_at)>julianday('now')",userId))fail('ANNUAL_DOWNGRADE_NOT_ALLOWED',409);const s=await settings(e),p=plan(s,planId);try{await run(e,'INSERT INTO entitlement_grants(source_type,source_ref,user_id,plan_id,license_key,device_limit,daily_limit) VALUES(?,?,?,?,?,?,?)',type,source,userId,planId,key('MHP'),s.allowed_devices,p.dailyLeadLimit)}catch(err){const won=await first(e,'SELECT user_id FROM entitlement_grants WHERE source_type=? AND source_ref=?',type,source);if(!won||won.user_id!==userId)throw err;}const g=await first(e,'SELECT l.license_key,s.expires_at FROM entitlement_grants g JOIN licenses l ON l.id=g.license_id JOIN subscriptions s ON s.id=g.subscription_id WHERE source_type=? AND source_ref=?',type,source);return {licenseKey:g.license_key,expiresAt:g.expires_at}}
async function ownerAccess(e,x){const code=String(x.licenseKey||'').trim().toUpperCase();if(!code.startsWith('MHP-OWNER-'))return null;if(code.length>100||!String(x.deviceId||'').trim()||String(x.deviceId).length>128)fail('LICENSE_AND_DEVICE_REQUIRED');const owner=await first(e,"SELECT id FROM owner_access WHERE id=1 AND status='active' AND code_hash=?",await hash(code));if(!owner)fail('INVALID_LICENSE',401);return {ok:true,valid:true,license:{planId:'owner',dailyLeadLimit:null,deviceLimit:null,expiresAt:null,owner:true},usedToday:0}}
async function license(r,e,x){const k=String(x.licenseKey||'').trim().toUpperCase(),device=String(x.deviceId||'').trim();if(!k||!device||device.length>128)fail('LICENSE_AND_DEVICE_REQUIRED');const l=await first(e,"SELECT l.*,s.plan_id,s.daily_lead_limit,u.email FROM licenses l JOIN subscriptions s ON s.id=l.subscription_id JOIN users u ON u.id=l.user_id WHERE l.license_key=? AND l.status='active' AND s.status='active' AND u.status='active' AND julianday(l.expires_at)>julianday('now') AND julianday(s.expires_at)>julianday('now')",k);if(!l)fail('INVALID_LICENSE',401);if(x.email&&email(x.email)!==email(l.email))fail('LICENSE_EMAIL_MISMATCH',403);let d=await first(e,'SELECT id,status FROM devices WHERE license_id=? AND device_uid=?',l.id,device);if(d?.status==='blocked')fail('DEVICE_BLOCKED',403);if(!d){try{await run(e,"INSERT INTO devices(user_id,license_id,device_uid,os,browser,last_ip,status) VALUES(?,?,?,?,?,?,'trusted')",l.user_id,l.id,device,String(x.os||'').slice(0,100),String(x.browser||'').slice(0,100),r.headers.get('cf-connecting-ip'))}catch(err){d=await first(e,'SELECT status FROM devices WHERE license_id=? AND device_uid=?',l.id,device);if(!d)fail('DEVICE_LIMIT_REACHED',403);if(d.status==='blocked')fail('DEVICE_BLOCKED',403)}}return l}
async function activation(r,e,x,u){const s=await settings(e),p=plan(s,x.planId),method=String(x.paymentMethod||'').trim().toUpperCase();if(!['USDT','REDOTPAY'].includes(method))fail('INVALID_PAYMENT_METHOD');const ref=String(x.referralCode||'').trim().toUpperCase();if(ref&&!await first(e,"SELECT id FROM payments WHERE user_id=? AND status='confirmed'",u.id)){await run(e,"INSERT OR IGNORE INTO referrals(affiliate_id,referred_user_id) SELECT id,? FROM affiliates WHERE referral_code=? AND status='active' AND lower(email)!=?",u.id,ref,u.email)}let old=await first(e,"SELECT a.request_ref,a.payment_ref,a.plan_id,p.amount_cents,p.method FROM activation_requests a JOIN payments p ON p.payment_ref=a.payment_ref WHERE a.user_id=? AND a.plan_id=? AND a.status='pending' AND p.status='pending' ORDER BY a.id DESC LIMIT 1",u.id,p.id);if(old&&old.method!==method){await e.DB.batch([sql(e,"UPDATE activation_requests SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE request_ref=?",old.request_ref),sql(e,"UPDATE payments SET status='rejected' WHERE payment_ref=? AND status='pending'",old.payment_ref)]);old=null}if(!old){await e.DB.batch([sql(e,"UPDATE activation_requests SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND status='pending'",u.id),sql(e,"UPDATE payments SET status='rejected' WHERE user_id=? AND status='pending' AND payment_ref IN (SELECT payment_ref FROM activation_requests WHERE user_id=?)",u.id,u.id)]);const ar=key('ACT'),pay=key('PAY');await e.DB.batch([sql(e,"INSERT INTO payments(payment_ref,user_id,method,amount_cents,payment_type,status) VALUES(?,?,?,?,?,'pending')",pay,u.id,method,Math.round(p.price*100),'first_purchase'),sql(e,"INSERT INTO activation_requests(request_ref,user_id,plan_id,payment_ref) VALUES(?,?,?,?)",ar,u.id,p.id,pay)]);old={request_ref:ar,payment_ref:pay,plan_id:p.id,amount_cents:Math.round(p.price*100),method}}return json({ok:true,requestRef:old.request_ref,paymentRef:old.payment_ref,planId:old.plan_id,amount:old.amount_cents/100,paymentMethod:old.method,status:'pending'},201)}
async function dispatch(r,e){const url=new URL(r.url),p=url.pathname,m=r.method;if(m==='OPTIONS')return new Response(null,{status:204,headers:HEADERS});if(p==='/api/health'){await ensureAuthSchema(e);return json({ok:true,version:'5.4.0-manual-payments',database:(await first(e,'SELECT 1 ok')).ok===1?'connected':'error',authentication:(await first(e,"SELECT name FROM sqlite_master WHERE type='table' AND name='auth_credentials'"))?'ready':'error'})}if(p==='/api/plans') {const s=await settings(e);return json({ok:true,plans:['monthly','annual'].map(id=>plan(s,id)),affiliate:{firstPurchasePercent:s.affiliate_first_purchase_percent,renewalPercent:s.affiliate_renewal_percent}})}
if(['/api/auth/register','/api/auth/login','/api/admin/login','/api/codes/redeem'].includes(p)&&m==='POST')await rateLimit(r,e,p);
if(p==='/api/admin/login'&&m==='POST'){await ensureAuthSchema(e);const x=await body(r);if(!e.ADMIN_TOKEN||x.username!==(e.ADMIN_USERNAME||'anasbm')||await hash(String(x.password||''))!==await hash(e.ADMIN_TOKEN))fail('INVALID_ADMIN_CREDENTIALS',401);const t=random(32);await run(e,"INSERT INTO admin_sessions(token_hash,expires_at) VALUES(?,datetime('now','+4 hours'))",await hash(t));await audit(e,'ADMIN_LOGIN',x.username,'session','created',{ip:r.headers.get('cf-connecting-ip')});return json({ok:true,token:t})}
if(['/api/auth/login','/api/auth/register'].includes(p)&&m==='POST'){await ensureAuthSchema(e);const x=await body(r),em=email(x.email),pw=String(x.password||'');if(!validEmail(em)||pw.length<8||pw.length>256)fail('INVALID_INPUT');let u=await first(e,'SELECT id,email,name,status FROM users WHERE email=?',em),credential=u?await first(e,'SELECT password_hash,password_salt,iterations FROM auth_credentials WHERE user_id=?',u.id):null;if(p.endsWith('/register')){if(u)fail('ACCOUNT_EXISTS',409);const name=String(x.name||'').trim().slice(0,120);if(!name)fail('NAME_REQUIRED');try{await run(e,'INSERT INTO users(email,name,locale) VALUES(?,?,?)',em,name,['en','ar','ru','de','es'].includes(x.locale)?x.locale:'en')}catch(err){if(await first(e,'SELECT id FROM users WHERE email=?',em))fail('ACCOUNT_EXISTS',409);throw err}u=await first(e,'SELECT id,email,name,status FROM users WHERE email=?',em);const salt=random(16);await run(e,'INSERT INTO auth_credentials(user_id,password_hash,password_salt,iterations) VALUES(?,?,?,?)',u.id,await passwordHash(pw,salt),salt,PASSWORD_ITERATIONS);await run(e,'INSERT OR IGNORE INTO acquisition(user_id,source,campaign) VALUES(?,?,?)',u.id,String(x.source||'direct').slice(0,120),String(x.campaign||'').slice(0,120))}else if(!u||u.status!=='active'||!credential||await passwordHash(pw,credential.password_salt,Number(credential.iterations)||150000)!==credential.password_hash)fail('INVALID_CREDENTIALS',401);const t=random(32);await run(e,"INSERT INTO auth_sessions(user_id,token_hash,expires_at) VALUES(?,?,datetime('now','+30 days'))",u.id,await hash(t));return json({ok:true,token:t,user:{id:u.id,email:u.email,name:u.name}},p.endsWith('/register')?201:200)}
if(p==='/api/auth/logout'&&m==='POST'){const a=(r.headers.get('authorization')||'').replace(/^Bearer /,'');await run(e,'DELETE FROM auth_sessions WHERE token_hash=?',await hash(a));return json({ok:true})}
if(p==='/api/account/me'&&m==='GET'){const u=await session(r,e);return json({ok:true,user:u,subscription:await first(e,'SELECT * FROM subscriptions WHERE user_id=? ORDER BY id DESC LIMIT 1',u.id),license:await first(e,'SELECT license_key,status,device_limit,expires_at FROM licenses WHERE user_id=? ORDER BY id DESC LIMIT 1',u.id)})}
if(p==='/api/account/payments'&&m==='GET'){const u=await session(r,e);return json({ok:true,payments:await rows(e,'SELECT payment_ref,amount_cents,method,status,created_at,confirmed_at FROM payments WHERE user_id=? ORDER BY id DESC LIMIT 30',u.id)})}
if(p==='/api/payment-methods'&&m==='GET'){const z=Object.fromEntries((await rows(e,"SELECT key,value FROM settings WHERE key IN ('usdt_network','usdt_address','redotpay_id','support_contact')")).map(x=>[x.key,x.value]));return json({ok:true,methods:{USDT:{enabled:Boolean(z.usdt_address),network:z.usdt_network||null,address:z.usdt_address||null},REDOTPAY:{enabled:Boolean(z.redotpay_id),account:z.redotpay_id||null}},support:z.support_contact||null})}
if(/^\/api\/payments\/[^/]+\/submit$/.test(p)&&m==='POST'){const u=await session(r,e),ref=decodeURIComponent(p.split('/')[3]),x=await body(r),payment=await first(e,"SELECT * FROM payments WHERE payment_ref=? AND user_id=?",ref,u.id);if(!payment)fail('PAYMENT_NOT_FOUND',404);if(payment.status!=='pending')fail('PAYMENT_NOT_PENDING',409);const external=String(x.transactionReference||'').trim().slice(0,200),proof=String(x.proofUrl||'').trim().slice(0,1000);if(!external&&!proof)fail('PAYMENT_PROOF_REQUIRED');if(external){const duplicate=await first(e,"SELECT payment_ref FROM payments WHERE external_reference=? AND payment_ref!=?",external,ref);if(duplicate)fail('DUPLICATE_EXTERNAL_REFERENCE',409)}await run(e,"UPDATE payments SET external_reference=?,proof_url=? WHERE payment_ref=? AND user_id=? AND status='pending'",external||null,proof||null,ref,u.id);await audit(e,'PAYMENT_PROOF_SUBMITTED',u.email,'payment',ref,{method:payment.method,hasReference:Boolean(external),hasProof:Boolean(proof)});return json({ok:true,paymentRef:ref,status:'pending_review'})}
if(p==='/api/activation/request'&&m==='POST')return activation(r,e,await body(r),await session(r,e));
if(p==='/api/codes/redeem'&&m==='POST'){const u=await session(r,e),x=await body(r),c=String(x.code||'').trim().toUpperCase();const z=await first(e,'SELECT * FROM activation_codes WHERE code=?',c);if(!z)fail('CODE_NOT_FOUND',404);if(z.status==='redeemed')fail('CODE_ALREADY_USED',409);if(z.status!=='unused')fail('CODE_NOT_AVAILABLE',409);if(z.expires_at&&Date.parse(z.expires_at)<=Date.now())fail('CODE_EXPIRED',410);return json({ok:true,planId:z.plan_id,...await grant(e,'code',c,u.id,z.plan_id)})}
if(['/api/license/validate','/api/usage/consume'].includes(p)&&m==='POST'){const x=await body(r);const owner=await ownerAccess(e,x);if(owner)return json(owner);const l=await license(r,e,x);if(p.endsWith('/consume')){const id=String(x.requestId||''),amount=Number(x.amount||1);if(id.length<8||id.length>128||!Number.isInteger(amount)||amount<1||amount>100)fail('INVALID_USAGE');const prior=await first(e,'SELECT user_id,license_id,amount FROM usage_events WHERE request_id=?',id);if(prior&&(prior.user_id!==l.user_id||prior.license_id!==l.id||prior.amount!==amount))fail('REQUEST_ID_CONFLICT',409);if(!prior)await run(e,"INSERT INTO usage_events(request_id,user_id,license_id,usage_date,amount) VALUES(?,?,?,date('now'),?)",id,l.user_id,l.id,amount)}const used=await first(e,"SELECT leads_processed FROM usage_daily WHERE user_id=? AND usage_date=date('now')",l.user_id);return json({ok:true,valid:true,license:{key:l.license_key,planId:l.plan_id,dailyLeadLimit:l.daily_lead_limit,deviceLimit:l.device_limit,expiresAt:l.expires_at,email:l.email},usedToday:used?.leads_processed||0})}
if(p==='/api/affiliate/register'&&m==='POST'){const u=await session(r,e),s=await settings(e);await run(e,"INSERT OR IGNORE INTO affiliates(email,name,referral_code,status,first_purchase_percent,renewal_percent) VALUES(?,?,?,'active',?,?)",u.email,u.name,key('AF'),s.affiliate_first_purchase_percent,s.affiliate_renewal_percent);return json({ok:true,affiliate:await first(e,'SELECT referral_code,status,first_purchase_percent,renewal_percent FROM affiliates WHERE email=?',u.email)})}
if(p==='/api/affiliate/me'&&m==='GET'){const u=await session(r,e),a=await first(e,"SELECT * FROM affiliates WHERE email=? AND status='active'",u.email);if(!a)fail('AFFILIATE_NOT_FOUND',404);const stats=await first(e,"SELECT (SELECT count(*) FROM referrals WHERE affiliate_id=?) referrals,(SELECT count(*) FROM referrals WHERE affiliate_id=? AND converted_at IS NOT NULL) conversions,(SELECT coalesce(sum(amount_cents),0) FROM commissions WHERE affiliate_id=? AND status IN ('approved','paid')) earned_cents,(SELECT coalesce(sum(c.amount_cents),0) FROM commissions c LEFT JOIN payout_commissions pc ON pc.commission_id=c.id WHERE c.affiliate_id=? AND c.status='approved' AND pc.commission_id IS NULL) available_cents",a.id,a.id,a.id,a.id);return json({ok:true,affiliate:{referralCode:a.referral_code,firstPurchasePercent:a.first_purchase_percent,renewalPercent:a.renewal_percent},stats,payouts:await rows(e,'SELECT payout_ref,amount_cents,method,destination,status,created_at,processed_at FROM payouts WHERE affiliate_id=? ORDER BY id DESC LIMIT 50',a.id)})}
if(p==='/api/affiliate/payouts'&&m==='POST'){const u=await session(r,e),x=await body(r),a=await first(e,"SELECT id FROM affiliates WHERE email=? AND status='active'",u.email);if(!a)fail('AFFILIATE_NOT_FOUND',404);if(!['USDT','REDOTPAY'].includes(x.method)||String(x.destination||'').trim().length<4)fail('INVALID_PAYOUT');const cs=await rows(e,"SELECT c.id,c.amount_cents FROM commissions c LEFT JOIN payout_commissions pc ON pc.commission_id=c.id WHERE c.affiliate_id=? AND c.status='approved' AND pc.commission_id IS NULL ORDER BY c.id",a.id);const amount=cs.reduce((n,c)=>n+Number(c.amount_cents),0);if(amount<=0)fail('NO_AVAILABLE_BALANCE',409);const ref=key('PO');await e.DB.batch([sql(e,"INSERT INTO payouts(payout_ref,affiliate_id,amount_cents,method,destination,status) VALUES(?,?,?,?,?,'pending')",ref,a.id,amount,x.method,String(x.destination).trim().slice(0,200)),...cs.map(c=>sql(e,'INSERT INTO payout_commissions(payout_id,commission_id,amount_cents) SELECT id,?,? FROM payouts WHERE payout_ref=?',c.id,c.amount_cents,ref))]);return json({ok:true,payoutRef:ref,amountCents:amount},201)}
if(p==='/api/account/data-request'&&m==='POST'){const u=await session(r,e),x=await body(r);if(!['access','correction','deletion'].includes(x.type))fail('INVALID_REQUEST_TYPE');const ref=key('DR');await run(e,'INSERT INTO data_requests(request_ref,user_id,request_type,note) VALUES(?,?,?,?)',ref,u.id,x.type,String(x.note||'').slice(0,1000));return json({ok:true,requestRef:ref,status:'pending'},201)}
if(p.startsWith('/api/admin/')){await session(r,e,true);return admin(r,e,url)}fail('NOT_FOUND',404)}
async function admin(r,e,url){const p=url.pathname,m=r.method;const limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit'))||50)),offset=Math.max(0,Number(url.searchParams.get('offset'))||0),q='%'+String(url.searchParams.get('q')||'').slice(0,120)+'%';
if(p==='/api/admin/owner-access'&&m==='GET')return json({ok:true,owner:await first(e,'SELECT status,created_at,updated_at FROM owner_access WHERE id=1')});
if(p==='/api/admin/owner-access/rotate'&&m==='POST'){const code='MHP-OWNER-'+random(32).toUpperCase();await e.DB.batch([sql(e,"INSERT INTO owner_access(id,code_hash,status) VALUES(1,?,'active') ON CONFLICT(id) DO UPDATE SET code_hash=excluded.code_hash,status='active',updated_at=CURRENT_TIMESTAMP",await hash(code)),sql(e,"INSERT INTO audit_logs(event_type,actor_type,actor,target_type,target_id,result) VALUES('OWNER_CODE_ROTATED','admin','admin','owner_access','1','success')")]);return json({ok:true,code,note:'Store this owner code securely. It will not be shown again.'})}
if(p==='/api/admin/summary'){const count=async(q)=>Number((await first(e,q)).c||0);const active="status='active' AND julianday(expires_at)>julianday('now')";const s={users:await count('SELECT count(*) c FROM users'),activeUsers:await count("SELECT count(*) c FROM users WHERE status='active'"),pendingActivations:await count("SELECT count(*) c FROM activation_requests WHERE status='pending'"),activeSubscriptions:await count('SELECT count(*) c FROM subscriptions WHERE '+active),activeLicenses:await count('SELECT count(*) c FROM licenses WHERE '+active),unusedCodes:await count("SELECT count(*) c FROM activation_codes WHERE status='unused' AND (expires_at IS NULL OR julianday(expires_at)>julianday('now'))"),monthlyRevenue:await count("SELECT coalesce(sum(amount_cents),0) c FROM payments WHERE status='confirmed' AND strftime('%Y-%m',confirmed_at)=strftime('%Y-%m','now')")/100,leadsToday:await count("SELECT coalesce(sum(leads_processed),0) c FROM usage_daily WHERE usage_date=date('now')"),pendingPayments:await count("SELECT count(*) c FROM payments WHERE status='pending'"),activeAffiliates:await count("SELECT count(*) c FROM affiliates WHERE status='active'"),expiringSoon:await count("SELECT count(*) c FROM subscriptions WHERE status='active' AND julianday(expires_at)>julianday('now') AND julianday(expires_at)<=julianday('now','+3 days')")};return json({ok:true,summary:s})}
let a=p.match(/^\/api\/admin\/activation-requests\/([^/]+)\/activate$/);if(a&&m==='POST'){const z=await first(e,'SELECT * FROM activation_requests WHERE request_ref=?',decodeURIComponent(a[1]));if(!z)fail('NOT_FOUND',404);if(z.status==='approved')return json({ok:true,already:true});return json({ok:true,...await grant(e,'payment',z.payment_ref,z.user_id,z.plan_id)})}
a=p.match(/^\/api\/admin\/payments\/([^/]+)\/confirm$/);if(a&&m==='POST'){const ref=decodeURIComponent(a[1]),x=await body(r),z=await first(e,'SELECT * FROM activation_requests WHERE payment_ref=?',ref);if(!z)fail('ACTIVATION_REQUEST_REQUIRED',409);if(z.status==='approved')return json({ok:true,already:true});const external=String(x.externalReference||'').trim().slice(0,200);if(external){const duplicate=await first(e,"SELECT payment_ref FROM payments WHERE external_reference=? AND payment_ref!=?",external,ref);if(duplicate)fail('DUPLICATE_EXTERNAL_REFERENCE',409);await run(e,"UPDATE payments SET external_reference=? WHERE payment_ref=? AND status='pending'",external,ref)}const result=await grant(e,'payment',z.payment_ref,z.user_id,z.plan_id);await audit(e,'PAYMENT_CONFIRMED','admin','payment',ref,{externalReference:external||null});return json({ok:true,...result})}
a=p.match(/^\/api\/admin\/payments\/([^/]+)\/refund$/);if(a&&m==='POST'){const ref=decodeURIComponent(a[1]),p0=await first(e,"SELECT * FROM payments WHERE payment_ref=? AND status='confirmed'",ref);if(!p0)fail('PAYMENT_NOT_CONFIRMED',409);await e.DB.batch([sql(e,"UPDATE payments SET status='refunded' WHERE id=? AND status='confirmed'",p0.id),sql(e,"UPDATE commissions SET status='cancelled' WHERE payment_id=? AND status!='paid'",p0.id),sql(e,"UPDATE licenses SET status='revoked',updated_at=CURRENT_TIMESTAMP WHERE subscription_id=?",p0.subscription_id),sql(e,"UPDATE subscriptions SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=?",p0.subscription_id)]);await audit(e,'PAYMENT_REFUNDED','admin','payment',ref,{amountCents:p0.amount_cents});return json({ok:true})}
const datasets={users:['users','SELECT id,email,name,status,locale,created_at FROM users WHERE email LIKE ? OR name LIKE ? ORDER BY id DESC'],payments:['payments','SELECT p.*,u.email FROM payments p JOIN users u ON u.id=p.user_id WHERE u.email LIKE ? OR p.payment_ref LIKE ? ORDER BY p.id DESC'],licenses:['licenses','SELECT l.*,u.email,s.plan_id FROM licenses l JOIN users u ON u.id=l.user_id LEFT JOIN subscriptions s ON s.id=l.subscription_id WHERE u.email LIKE ? OR l.license_key LIKE ? ORDER BY l.id DESC'],activations:['activation_requests','SELECT a.*,u.email,p.amount_cents,p.method,p.status payment_status,p.external_reference,p.proof_url FROM activation_requests a JOIN users u ON u.id=a.user_id LEFT JOIN payments p ON p.payment_ref=a.payment_ref WHERE u.email LIKE ? OR a.request_ref LIKE ? ORDER BY a.id DESC']};
for(const [name,[label,query]] of Object.entries(datasets)){if(p===`/api/admin/${name}`&&m==='GET')return json({ok:true,[label]:await rows(e,query+' LIMIT ? OFFSET ?',q,q,limit,offset)})}
fail('NOT_FOUND',404)}
async function maintenance(e){try{await run(e,"DELETE FROM auth_sessions WHERE julianday(expires_at)<=julianday('now')");await run(e,"DELETE FROM admin_sessions WHERE julianday(expires_at)<=julianday('now')")}catch{}}
export default {async fetch(r,e){try{return await dispatch(r,e)}catch(err){const message=String(err.message||err);const known=['CODE_NOT_AVAILABLE','PAYMENT_NOT_PENDING','ACCOUNT_INACTIVE','ANNUAL_DOWNGRADE_NOT_ALLOWED','DAILY_LIMIT_REACHED','INVALID_LICENSE','DEVICE_LIMIT_REACHED','DUPLICATE_EXTERNAL_REFERENCE'].find(x=>message.includes(x));return json({ok:false,error:err.status?message:known||'SERVER_ERROR'},err.status||(known?409:500))}},async scheduled(c,e,ctx){ctx.waitUntil(maintenance(e))}};