const API_BASE = window.MHP_API_BASE || '';
let token = sessionStorage.getItem('mhp_admin_token') || '';
let currentView = 'overview';
let lastRows = {};
const pageState={};
let searchTimer=null;

const $ = id => document.getElementById(id);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = cents => `$${(Number(cents||0)/100).toFixed(2)}`;
const date = v => v ? new Date(String(v).replace(' ','T')+'Z').toLocaleString() : '—';
const pill = s => `<span class="pill ${['active','confirmed','trusted','allowed','paid'].includes(s)?'green':['pending','review'].includes(s)?'orange':['revoked','expired','blocked','rejected'].includes(s)?'red':'gray'}">${esc(s||'—')}</span>`;
function toast(msg){ const t=$('toast'); t.textContent=msg; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),3000); }

function installCodesUI(){
  const settingsNav=document.querySelector('[data-view="settings"]');
  settingsNav.insertAdjacentHTML('beforebegin','<button class="nav-item" data-view="codes"><span class="ico">#</span> Activation codes</button>');
  $('settings').insertAdjacentHTML('beforebegin',`<section class="view" id="codes"><div class="page-head"><div><h1>Activation codes</h1><p>Generate, inspect and revoke single-use codes.</p></div><button class="primary-btn" id="generateCodesBtn">+ Generate codes</button></div><div class="card panel"><div class="form-grid"><div class="field"><label>Plan</label><select id="codePlan"><option value="monthly">Monthly — $20</option><option value="annual">Annual — $100</option></select></div><div class="field"><label>Quantity (1–100)</label><input id="codeQuantity" type="number" min="1" max="100" value="1"></div><div class="field"><label>Purchaser email (optional)</label><input id="codeEmail" type="email"></div><div class="field"><label>Expiry (optional)</label><input id="codeExpiry" type="datetime-local"></div></div><div class="field" style="margin-top:12px"><label>Note (optional)</label><input id="codeNote" maxlength="500"></div></div><div class="card table-card" style="margin-top:18px"><div class="table-wrap"><table><thead><tr><th>Code</th><th>Plan</th><th>Status</th><th>Purchaser</th><th>Redeemed by</th><th>Expires</th><th>Action</th></tr></thead><tbody id="codesBody"></tbody></table></div></div></section>`);
}
installCodesUI();

async function api(path, options={}) {
  const headers = {'content-type':'application/json', ...(options.headers||{})};
  if(token) headers.authorization=`Bearer ${token}`;
  const r=await fetch(API_BASE+path,{...options,headers});
  let data={}; try{data=await r.json()}catch{}
  if(r.status===401){ sessionStorage.removeItem('mhp_admin_token'); token=''; $('loginGate').style.display='flex'; throw new Error('Unauthorized'); }
  if(!r.ok || data.ok===false) throw new Error(data.error||`HTTP ${r.status}`);
  return data;
}
async function listApi(name){const s=pageState[name]||(pageState[name]={offset:0,q:'',hasMore:false,limit:50});const d=await api(`/api/admin/${name}?limit=${s.limit}&offset=${s.offset}&q=${encodeURIComponent(s.q)}`);s.hasMore=Boolean(d.hasMore);return d;}
function renderPager(view){const table=$(view)?.querySelector('.table-card');if(!table)return;let bar=table.querySelector('.pager');if(!bar){bar=document.createElement('div');bar.className='pager';bar.style.cssText='display:flex;justify-content:flex-end;align-items:center;gap:10px;padding:12px 16px';table.appendChild(bar);}const s=pageState[view];if(!s){bar.innerHTML='';return;}bar.innerHTML=`<button class="mini" data-page="prev" ${s.offset?'':'disabled'}>Previous</button><span class="email">${s.offset+1}–${s.offset+s.limit}</span><button class="mini" data-page="next" ${s.hasMore?'':'disabled'}>Next</button>`;}

async function login(){
  const password=$('adminTokenInput').value; $('loginError').textContent='';
  if(!password){$('loginError').textContent='Enter the admin password.';return;}
  try{const d=await api('/api/admin/login',{method:'POST',body:JSON.stringify({username:'anasbm',password})});token=d.token;sessionStorage.setItem('mhp_admin_token',token);$('loginGate').style.display='none';await refreshAll();}
  catch(e){$('loginError').textContent='Invalid token or API unavailable.';}
}

async function health(){
  try{const d=await fetch(API_BASE+'/api/health').then(r=>r.json());const ok=d.ok&&d.database==='connected';$('apiStatus').textContent=ok?'API: online':'API: error';$('sidebarStatus').textContent=ok?'● API + D1 operational':'● API issue';$('sidebarStatus').style.color=ok?'#9be5bb':'#ffb4b4';}
  catch{$('apiStatus').textContent='API: offline';$('sidebarStatus').textContent='● API offline';}
}

async function loadOverview(){ const d=await api('/api/admin/summary'); const s=d.summary; $('sActiveUsers').textContent=s.activeUsers; $('sRevenue').textContent=`$${Number(s.monthlyRevenue).toFixed(2)}`; $('sLicenses').textContent=s.activeLicenses; $('sExpiring').textContent=`${s.expiringSoon} expiring soon`; $('sLeads').textContent=Number(s.leadsToday).toLocaleString(); $('sSubs').textContent=s.activeSubscriptions; $('sPending').textContent=s.pendingPayments; $('sAffiliates').textContent=s.activeAffiliates; }
async function loadUsers(){const d=await listApi('users');lastRows.users=d.users;$('usersBody').innerHTML=d.users.map(x=>`<tr><td>${x.id}</td><td><strong>${esc(x.name||'—')}</strong><div class="email">${esc(x.email)}</div></td><td>${esc(x.plan_id||'—')}</td><td>${pill(x.subscription_status)}</td><td>${date(x.expires_at)}</td><td>${x.devices}</td><td>${pill(x.status)}</td></tr>`).join('')||empty(7);}
async function loadSubscriptions(){const d=await listApi('subscriptions');lastRows.subscriptions=d.subscriptions;$('subscriptionsBody').innerHTML=d.subscriptions.map(x=>`<tr><td>${x.id}</td><td>${esc(x.email)}</td><td>${esc(x.plan_id)}</td><td>${pill(x.status)}</td><td>${date(x.started_at)}</td><td>${date(x.expires_at)}</td><td>${x.daily_lead_limit==null?'Unlimited':x.daily_lead_limit}</td></tr>`).join('')||empty(7);}
async function loadLicenses(){const d=await listApi('licenses');lastRows.licenses=d.licenses;$('licensesBody').innerHTML=d.licenses.map(x=>`<tr><td class="mono"><strong>${esc(x.license_key)}</strong></td><td>${esc(x.email)}</td><td>${esc(x.plan_id||'—')}</td><td>${pill(x.status)}</td><td>${x.device_limit}</td><td>${date(x.expires_at)}</td><td>${x.status==='active'?`<button class="mini" data-revoke="${esc(x.license_key)}">Revoke</button>`:'—'}</td></tr>`).join('')||empty(7);}
async function loadDevices(){const d=await listApi('devices');lastRows.devices=d.devices;$('devicesBody').innerHTML=d.devices.map(x=>`<tr><td class="mono">${esc(x.device_uid)}</td><td>${esc(x.email)}</td><td class="mono">${esc(x.license_key)}</td><td>${esc(x.os||'—')}</td><td>${esc(x.browser||'—')}</td><td>${esc(x.last_ip||'—')}</td><td>${pill(x.status)}</td><td>${date(x.last_seen_at)}<div class="row-actions"><button class="mini" data-device-action="${x.status==='blocked'?'unblock':'block'}" data-device-id="${x.id}">${x.status==='blocked'?'Unblock':'Block'}</button><button class="mini" data-device-action="release" data-device-id="${x.id}">Release</button></div></td></tr>`).join('')||empty(8);}
async function loadPayments(){const d=await listApi('payments');lastRows.payments=d.payments;$('paymentsBody').innerHTML=d.payments.map(x=>`<tr><td class="mono">${esc(x.payment_ref)}<div class="email">${esc(x.external_reference||'')}</div></td><td>${esc(x.email)}</td><td>${esc(x.method)}</td><td>${money(x.amount_cents)}</td><td>${esc(x.payment_type)}</td><td>${pill(x.status)}</td><td>${date(x.created_at)}</td><td>${x.status==='pending'?`<button class="mini" data-confirm-payment="${esc(x.payment_ref)}">Confirm</button>`:x.status==='confirmed'?`<button class="mini" data-refund-payment="${esc(x.payment_ref)}">Refund</button>`:'—'}</td></tr>`).join('')||empty(8);}
async function loadAffiliates(){const d=await listApi('affiliates');lastRows.affiliates=d.affiliates;$('affiliatesBody').innerHTML=d.affiliates.map(x=>`<tr><td>${x.id}</td><td><strong>${esc(x.name||'—')}</strong><div class="email">${esc(x.email)}</div></td><td class="mono">${esc(x.referral_code)}</td><td>${x.referrals}</td><td>${money(x.commission_cents)}</td><td>${x.first_purchase_percent}%</td><td>${x.renewal_percent}%</td><td>${pill(x.status)}</td></tr>`).join('')||empty(8);}
async function loadPayouts(){const d=await listApi('payouts');lastRows.payouts=d.payouts;$('payoutsBody').innerHTML=d.payouts.map(x=>`<tr><td>${esc(x.payout_ref)}</td><td>${esc(x.email)}</td><td>${money(x.amount_cents)}</td><td>${esc(x.method)}</td><td>${esc(x.destination)}</td><td>${pill(x.status)}</td><td>${date(x.created_at)}<div class="row-actions">${x.status==='pending'?`<button class="mini" data-payout-action="approve" data-payout="${esc(x.payout_ref)}">Approve</button><button class="mini" data-payout-action="reject" data-payout="${esc(x.payout_ref)}">Reject</button>`:x.status==='approved'?`<button class="mini" data-payout-action="pay" data-payout="${esc(x.payout_ref)}">Mark paid</button>`:''}</div></td></tr>`).join('')||empty(7);}
async function loadUsage(){const d=await listApi('usage');lastRows.usage=d.usage;$('usageBody').innerHTML=d.usage.map(x=>`<tr><td>${esc(x.usage_date)}</td><td>${esc(x.email)}</td><td>${Number(x.leads_processed).toLocaleString()}</td><td>${x.api_errors}</td><td>${date(x.updated_at)}</td></tr>`).join('')||empty(5);}
async function loadLogs(){const d=await listApi('logs');lastRows.logs=d.logs;$('logsBody').innerHTML=d.logs.map(x=>`<tr><td>${date(x.created_at)}</td><td>${esc(x.event_type)}</td><td>${esc(x.actor||x.actor_type)}</td><td>${esc([x.target_type,x.target_id].filter(Boolean).join(': ')||'—')}</td><td>${esc(x.ip||'—')}</td><td>${pill(x.result)}</td></tr>`).join('')||empty(6);}
async function loadCodes(){const d=await listApi('codes');lastRows.codes=d.codes;$('codesBody').innerHTML=d.codes.map(x=>`<tr><td class="mono"><strong>${esc(x.code)}</strong></td><td>${esc(x.plan_id)}</td><td>${pill(x.status)}</td><td>${esc(x.purchaser_email||'—')}</td><td>${esc(x.redeemed_by_email||'—')}</td><td>${date(x.expires_at)}</td><td>${x.status==='unused'?`<button class="mini" data-revoke-code="${esc(x.code)}">Revoke</button>`:'—'}</td></tr>`).join('')||empty(7);}
async function loadSettings(){const d=await api('/api/admin/settings');const s=Object.fromEntries(d.settings.map(x=>[x.key,x.value]));$('setMonthlyPrice').value=s.monthly_price_usd||20;$('setAnnualPrice').value=s.annual_price_usd||100;$('setMonthlyLimit').value=s.monthly_daily_limit||1500;$('setAnnualLimit').value=s.annual_daily_limit||'unlimited';$('setFirstCommission').value=s.affiliate_first_purchase_percent||50;$('setRenewCommission').value=s.affiliate_renewal_percent||20;$('setDevices').value=s.allowed_devices||2;$('setPayments').value=s.payment_methods||'USDT,REDOTPAY';}
function empty(n){return `<tr><td colspan="${n}" class="empty">No records yet.</td></tr>`;}
const loaders={overview:loadOverview,users:loadUsers,subscriptions:loadSubscriptions,licenses:loadLicenses,codes:loadCodes,devices:loadDevices,payments:loadPayments,affiliates:loadAffiliates,payouts:loadPayouts,usage:loadUsage,logs:loadLogs,settings:loadSettings};
async function loadView(view){try{document.querySelector('.content').classList.add('loading');await loaders[view]?.();renderPager(view);}catch(e){toast(e.message);}finally{document.querySelector('.content').classList.remove('loading');}}
async function refreshAll(){await health();await loadView(currentView);}

async function createLicense(){try{const body={email:$('licEmail').value.trim(),name:$('licName').value.trim(),planId:$('licPlan').value,deviceLimit:Number($('licDevices').value)};const d=await api('/api/admin/licenses',{method:'POST',body:JSON.stringify(body)});$('licenseModal').classList.remove('open');toast(`Created: ${d.license.licenseKey}`);await loadOverview();await loadLicenses();}catch(e){toast(e.message);}}
async function revoke(key){if(!confirm(`Revoke ${key}?`))return;try{await api(`/api/admin/licenses/${encodeURIComponent(key)}/revoke`,{method:'POST',body:'{}'});toast('License revoked');await loadLicenses();await loadOverview();}catch(e){toast(e.message);}}
async function confirmPayment(ref){const external=prompt('External transaction/reference (optional):','')||'';if(!confirm(`Confirm payment ${ref}? This activates a subscription.`))return;try{await api(`/api/admin/payments/${encodeURIComponent(ref)}/confirm`,{method:'POST',body:JSON.stringify({externalReference:external})});toast('Payment confirmed');await loadPayments();await loadOverview();await loadSubscriptions();}catch(e){toast(e.message);}}
async function refundPayment(ref){if(!confirm(`Refund ${ref}? This revokes the related entitlement.`))return;try{await api(`/api/admin/payments/${encodeURIComponent(ref)}/refund`,{method:'POST',body:'{}'});toast('Payment refunded');await loadPayments();await loadOverview();}catch(e){toast(e.message);}}
async function deviceAction(id,action){if(!confirm(`${action} device ${id}?`))return;try{await api(`/api/admin/devices/${id}/${action}`,{method:'POST',body:'{}'});toast(`Device ${action} complete`);await loadDevices();}catch(e){toast(e.message);}}
async function payoutAction(ref,action){if(!confirm(`${action} payout ${ref}?`))return;try{await api(`/api/admin/payouts/${encodeURIComponent(ref)}/${action}`,{method:'POST',body:'{}'});toast(`Payout ${action} complete`);await loadPayouts();}catch(e){toast(e.message);}}
async function generateCodes(){try{const expires=$('codeExpiry').value;const d=await api('/api/admin/codes/generate',{method:'POST',body:JSON.stringify({planId:$('codePlan').value,quantity:Number($('codeQuantity').value),purchaserEmail:$('codeEmail').value.trim(),expiresAt:expires?new Date(expires).toISOString():null,note:$('codeNote').value.trim()})});toast(`Generated ${d.codes.length} code(s)`);await loadCodes();await loadOverview();}catch(e){toast(e.message);}}
async function revokeCode(code){if(!confirm(`Revoke ${code}?`))return;try{await api(`/api/admin/codes/${encodeURIComponent(code)}/revoke`,{method:'POST',body:'{}'});toast('Code revoked');await loadCodes();await loadOverview();}catch(e){toast(e.message);}}
async function saveSettings(){try{await api('/api/admin/settings',{method:'PATCH',body:JSON.stringify({monthly_price_usd:$('setMonthlyPrice').value,annual_price_usd:$('setAnnualPrice').value,monthly_daily_limit:$('setMonthlyLimit').value,affiliate_first_purchase_percent:$('setFirstCommission').value,affiliate_renewal_percent:$('setRenewCommission').value,allowed_devices:$('setDevices').value})});toast('Settings saved');}catch(e){toast(e.message);}}

document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));currentView=btn.dataset.view;$(currentView).classList.add('active');$('sidebar').classList.remove('open');loadView(currentView);}));
$('menuBtn').addEventListener('click',()=>$('sidebar').classList.toggle('open'));
$('loginBtn').addEventListener('click',login);$('adminTokenInput').addEventListener('keydown',e=>{if(e.key==='Enter')login();});
$('refreshBtn').addEventListener('click',refreshAll);$('logoutBtn').addEventListener('click',async()=>{try{await api('/api/admin/logout',{method:'POST',body:'{}'});}catch{}sessionStorage.removeItem('mhp_admin_token');token='';location.reload();});
document.querySelectorAll('[data-open-license]').forEach(x=>x.addEventListener('click',()=>$('licenseModal').classList.add('open')));$('closeModal').onclick=$('cancelModal').onclick=()=>$('licenseModal').classList.remove('open');$('createLicenseBtn').addEventListener('click',createLicense);$('saveSettingsBtn').addEventListener('click',saveSettings);
$('generateCodesBtn').addEventListener('click',generateCodes);
document.addEventListener('click',e=>{const r=e.target.closest('[data-revoke]');if(r)revoke(r.dataset.revoke);const c=e.target.closest('[data-revoke-code]');if(c)revokeCode(c.dataset.revokeCode);const p=e.target.closest('[data-confirm-payment]');if(p)confirmPayment(p.dataset.confirmPayment);const rf=e.target.closest('[data-refund-payment]');if(rf)refundPayment(rf.dataset.refundPayment);const dv=e.target.closest('[data-device-action]');if(dv)deviceAction(dv.dataset.deviceId,dv.dataset.deviceAction);const po=e.target.closest('[data-payout-action]');if(po)payoutAction(po.dataset.payout,po.dataset.payoutAction);const pg=e.target.closest('[data-page]');if(pg&&pageState[currentView]){const s=pageState[currentView];s.offset=Math.max(0,s.offset+(pg.dataset.page==='next'?s.limit:-s.limit));loadView(currentView);}});
$('searchInput').addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if(pageState[currentView]){pageState[currentView].q=e.target.value.trim();pageState[currentView].offset=0;loadView(currentView);}},300);});

health();
if(token){$('loginGate').style.display='none';refreshAll();}
