(()=>{
'use strict';
const $=id=>document.getElementById(id),API='',TOKEN='mhp_admin_session';
let token=sessionStorage.getItem(TOKEN)||'',customers=[],licenses=[],activeCustomerId=null,toastTimer;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v||0).toLocaleString();
const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(c||0)/100);
const date=v=>{if(!v)return '—';const raw=String(v),d=new Date(raw.includes('T')?raw:(raw.length===10?raw+'T00:00:00Z':raw+'Z'));return Number.isNaN(d.getTime())?raw:d.toLocaleString([],raw.length===10?{year:'numeric',month:'short',day:'numeric'}:{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})};
const flag=code=>{const s=String(code||'').trim().toUpperCase();return /^[A-Z]{2}$/.test(s)?String.fromCodePoint(...[...s].map(c=>127397+c.charCodeAt())):''};
function toast(m){const t=$('toast');if(!t)return;t.textContent=String(m||'');t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2300)}
async function api(path,opt={}){const h={'content-type':'application/json',...(opt.headers||{})};if(token)h.authorization='Bearer '+token;const r=await fetch(API+path,{...opt,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok||d.ok===false)throw new Error(d.error||`HTTP ${r.status}`);return d}
function showApp(ok){$('login').classList.toggle('hidden',ok);$('app').classList.toggle('hidden',!ok)}
function pill(s){const v=String(s||'unknown').toLowerCase();return `<span class="pill ${esc(v)}">${esc(v.replace(/-/g,' '))}</span>`}
function planName(x){return Number(x?.is_lifetime)===1?'Lifetime':x?.plan_id==='annual'?'Annual (legacy)':String(x?.plan_id||'—').replace(/^./,c=>c.toUpperCase())}
function expiry(x){return Number(x?.is_lifetime)===1?'Lifetime':date(x?.expires_at)}
async function login(e){e.preventDefault();try{const d=await api('/api/admin/login',{method:'POST',body:JSON.stringify({username:$('username').value.trim(),password:$('password').value})});token=d.token;sessionStorage.setItem(TOKEN,token);showApp(true);await refreshAll()}catch(err){$('loginError').textContent=err.message}}
async function logout(){try{await api('/api/admin/logout',{method:'POST',body:'{}'})}catch{}token='';sessionStorage.removeItem(TOKEN);showApp(false)}
function legacyCopyText(value){const f=document.createElement('textarea'),active=document.activeElement;f.value=String(value??'');f.setAttribute('readonly','');f.style.position='fixed';f.style.top='-1000px';document.body.appendChild(f);f.select();let ok=false;try{ok=document.execCommand('copy')===true}catch{}finally{f.remove();try{active?.focus?.()}catch{}}return ok}
async function copyField(id){const el=$(id),value=el&&'value'in el?el.value:el?.textContent||'';try{if(navigator.clipboard?.writeText&&window.isSecureContext)await navigator.clipboard.writeText(value);else if(!legacyCopyText(value))throw new Error();toast('Copied')}catch{toast('Copy failed')}}
function renderCustomerOptions(){const opts=customers.map(c=>`<option value="${c.id}">${esc(c.display_name)}${c.country_name?' · '+esc(c.country_name):''}</option>`).join('');if($('saleCustomer'))$('saleCustomer').innerHTML=opts||'<option value="">No customers</option>';if($('genCustomer'))$('genCustomer').innerHTML='<option value="">Unassigned</option>'+opts}
async function loadSummary(){const d=await api('/api/admin/summary'),s=d.summary;$('mRevenue').textContent=money(s.totalRevenueCents);$('mCustomers').textContent=num(s.customersCount);$('mCountries').textContent=`${num(s.countriesCount)} countries`;$('mTotalLeads').textContent=num(s.totalLeads);$('mLeads').textContent=num(s.leadsToday);$('m7d').textContent=`${num(s.leads7d)} last 7 days`;$('mSales').textContent=num(s.salesCount);$('mAvgSale').textContent=`${money(s.averageSaleCents)} avg sale`;$('mActive').textContent=num(s.activeLicenses);$('mSoon').textContent=`${num(s.expiringSoon)} expiring ≤3 days`;$('mAttention').textContent=num(s.attentionCustomers);$('mUnused').textContent=num(s.unusedCodes);
$('recentCustomers').innerHTML=(d.recentCustomers||[]).map(c=>`<tr><td><button class="ghost" data-open-customer="${c.id}">${esc(c.display_name)}</button></td><td>${flag(c.country_code)} ${esc(c.country_name||'—')}</td><td>${money(c.revenue_cents)}</td><td>${num(c.total_leads)}</td><td>${num(c.leads_today)}</td><td>${pill(c.health)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No customers yet</td></tr>';
const max=Math.max(1,...(d.countryRevenue||[]).map(x=>Number(x.revenue_cents||0)));$('countryRevenue').innerHTML=(d.countryRevenue||[]).map(x=>`<div class="chart-row"><span>${esc(x.country||'Unknown')}</span><div class="chart-track"><div class="chart-bar" style="width:${Math.max(3,Number(x.revenue_cents||0)/max*100)}%"></div></div><span class="chart-value">${money(x.revenue_cents)}</span></div>`).join('')||'<div class="empty">No sales recorded</div>'}
async function loadCustomers(){const q=encodeURIComponent($('customerSearch')?.value.trim()||''),d=await api('/api/admin/customers?q='+q);customers=d.customers||[];renderCustomerOptions();$('customersBody').innerHTML=customers.map(c=>`<tr><td><strong>${esc(c.display_name)}</strong><div class="tiny">${esc(c.contact||'')}</div></td><td>${flag(c.country_code)} ${esc(c.country_name||'—')}</td><td>${money(c.revenue_cents)}</td><td>${num(c.sales_count)}</td><td>${num(c.total_leads)}</td><td>${num(c.leads_today)}</td><td>${num(c.active_license_count)} / ${num(c.license_count)}</td><td>${date(c.last_usage_date||c.last_validated_at)}</td><td>${pill(c.health)}</td><td><button class="dark" data-open-customer="${c.id}">Open 360</button></td></tr>`).join('')||'<tr><td colspan="10" class="empty">No customers found</td></tr>';return customers}
async function createCustomer(){try{const d=await api('/api/admin/customers',{method:'POST',body:JSON.stringify({displayName:$('newCustomerName').value.trim(),countryName:$('newCustomerCountry').value.trim(),countryCode:$('newCustomerCode').value.trim(),contact:$('newCustomerContact').value.trim()})});['newCustomerName','newCustomerCountry','newCustomerCode','newCustomerContact'].forEach(id=>$(id).value='');$('addCustomerBox').classList.add('hidden');toast('Customer created');await Promise.all([loadCustomers(),loadSummary()]);if(d.customer)openCustomer(d.customer.id)}catch(e){toast(e.message)}}
async function loadSales(){const q=encodeURIComponent($('salesSearch')?.value.trim()||''),d=await api('/api/admin/sales?q='+q);$('salesBody').innerHTML=(d.sales||[]).map(x=>`<tr><td>#${x.id}</td><td><button class="ghost" data-open-customer="${x.customer_id}">${esc(x.customer_name)}</button></td><td>${esc(x.country_name||'—')}</td><td><strong>${money(x.amount_cents)}</strong></td><td>${esc(x.plan_label||'—')}</td><td>${esc(x.payment_method||'—')}</td><td>${date(x.sold_at||x.created_at)}</td><td class="mono">${esc(x.license_hint||'Unlinked')}</td><td>${pill(x.status)}</td><td class="mono">${esc(x.transaction_reference||'—')}</td></tr>`).join('')||'<tr><td colspan="10" class="empty">No sales</td></tr>'}
async function createSale(){try{const customerId=Number($('saleCustomer').value||0);if(!customerId)throw new Error('Choose a customer');await api('/api/admin/sales',{method:'POST',body:JSON.stringify({customerId,amountUsd:Number($('saleAmount').value||0),planLabel:$('salePlan').value.trim(),paymentMethod:$('saleMethod').value.trim()||'Manual',soldAt:$('saleDate').value||null})});['saleAmount','salePlan','saleMethod','saleDate'].forEach(id=>$(id).value='');$('addSaleBox').classList.add('hidden');toast('Sale recorded');await Promise.all([loadSales(),loadCustomers(),loadSummary()])}catch(e){toast(e.message)}}
async function loadLicenses(){const q=encodeURIComponent($('licenseSearch')?.value.trim()||''),d=await api('/api/admin/manual-licenses?q='+q);licenses=d.licenses||[];$('licensesBody').innerHTML=licenses.map(x=>`<tr><td>${x.id}</td><td>${x.customer_id?`<button class="ghost" data-open-customer="${x.customer_id}">${esc(x.customer_name||'Customer')}</button>`:'<span class="tiny">Unassigned</span>'}</td><td class="mono">${esc(x.code_hint)}</td><td>${esc(planName(x))}</td><td>${pill(x.status)}</td><td>${x.customer_id?'Linked':'—'}</td><td>${num(x.used_today)}${x.daily_lead_limit==null?'':' / '+num(x.daily_lead_limit)}</td><td><strong>${num(x.total_leads)}</strong></td><td>${date(x.last_usage_date||x.last_validated_at)}</td><td>${num(x.device_count)}/1</td><td>${pill(x.health)}</td><td><div class="actions">${x.status!=='revoked'?`<button data-extend="${x.id}" data-plan="monthly">+30d</button><button data-extend="${x.id}" data-plan="lifetime">Lifetime</button><button data-reset="${x.id}">Reset device</button><button class="danger" data-revoke="${x.id}">Revoke</button>`:'—'}</div></td></tr>`).join('')||'<tr><td colspan="12" class="empty">No licenses</td></tr>';return licenses}
async function generate(){try{const d=await api('/api/admin/manual-licenses',{method:'POST',body:JSON.stringify({planId:$('genPlan').value,count:Number($('genCount').value),note:$('genNote').value.trim(),customerId:$('genCustomer').value?Number($('genCustomer').value):null})});$('generatedCodes').value=d.codes.join('\n');$('generatedBox').classList.remove('hidden');toast(`Generated ${d.codes.length} code(s)`);await Promise.all([loadLicenses(),loadCustomers(),loadSummary()])}catch(e){toast(e.message)}}
async function licenseAction(id,act,planId){try{if(act==='revoke'&&!confirm('Revoke this code?'))return;await api(`/api/admin/manual-licenses/${id}/${act}`,{method:'POST',body:act==='extend'?JSON.stringify({planId}):'{}'});toast(act==='reset-devices'?'Device binding reset':'License updated');await Promise.all([loadLicenses(),loadCustomers(),loadSummary()]);if(activeCustomerId)openCustomer(activeCustomerId)}catch(e){toast(e.message)}}
async function loadSupport(){const [cd,ed]=await Promise.all([api('/api/admin/customers'),api('/api/admin/support-events')]);const attention=(cd.customers||[]).filter(x=>x.health!=='healthy');$('attentionList').innerHTML=attention.map(c=>`<div style="display:flex;justify-content:space-between;gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid var(--line)"><div><strong>${esc(c.display_name)}</strong><div class="tiny">${esc(c.country_name||'')} · ${num(c.total_leads)} leads</div></div><div>${pill(c.health)} <button class="ghost" data-open-customer="${c.id}">Open</button></div></div>`).join('')||'<div class="empty">No customers need attention</div>';
const events=ed.events||[];$('supportSummary').textContent=events.length?`${events.length} recent sanitized technical events`:'No technical events yet. The support telemetry schema is ready.';$('supportBody').innerHTML=events.map(x=>`<tr><td>${date(x.created_at)}</td><td>${esc(x.customer_name||'—')}</td><td class="mono">${esc(x.license_hint||'—')}</td><td>${esc(x.event_type)}</td><td>${esc(x.error_code||'—')}</td><td>${esc(x.extension_version||'—')}</td><td>${esc(x.phase||'—')}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No support events yet</td></tr>'}
async function openCustomer(id){try{activeCustomerId=Number(id);const d=await api(`/api/admin/customers/${activeCustomerId}`),c=d.customer;$('drawerCustomerName').textContent=c.display_name;$('drawerMeta').textContent=`${flag(c.country_code)} ${c.country_name||'Unknown country'} · ${c.health.replace(/-/g,' ')}`;$('dRevenue').textContent=money(c.revenue_cents);$('dLeads').textContent=num(c.total_leads);$('d30').textContent=num(d.metrics.leads30d);$('dPeak').textContent=num(d.metrics.peakDay);$('dContact').value=c.contact||'';$('dNote').value=c.note||'';
const usage=[...(d.usage||[])].reverse(),max=Math.max(1,...usage.map(x=>Number(x.leads||0)));$('usageBars').innerHTML=usage.map(x=>`<i title="${esc(x.usage_date)} · ${num(x.leads)} leads" style="height:${Math.max(3,Number(x.leads||0)/max*100)}%"></i>`).join('')||'<div class="empty">No usage yet</div>';$('usageCaption').textContent=`${d.metrics.activeDays} active days shown · ${num(d.metrics.leads7d)} leads in last 7 days`;
$('drawerLicenses').innerHTML=(d.licenses||[]).map(x=>`<tr><td class="mono">${esc(x.code_hint)}</td><td>${esc(planName(x))}</td><td>${pill(x.status)}</td><td>${num(x.total_leads)}</td><td>${num(x.used_today)}</td><td>${date(x.device_last_seen_at)}</td><td><button class="ghost" data-unlink-license="${x.id}">Unlink</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No linked licenses</td></tr>';$('drawerSales').innerHTML=(d.sales||[]).map(x=>`<tr><td>${money(x.amount_cents)}</td><td>${esc(x.plan_label||'—')}</td><td>${esc(x.payment_method||'—')}</td><td>${date(x.sold_at||x.created_at)}</td><td>${pill(x.status)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No sales</td></tr>';
const unlinked=licenses.filter(x=>!x.customer_id||Number(x.customer_id)===activeCustomerId);$('linkLicenseSelect').innerHTML='<option value="">Choose unassigned license</option>'+unlinked.map(x=>`<option value="${x.id}">${esc(x.code_hint)} · ${esc(planName(x))}</option>`).join('');$('customerDrawerBackdrop').classList.add('open')}catch(e){toast(e.message)}}
async function saveCustomerProfile(){try{await api(`/api/admin/customers/${activeCustomerId}`,{method:'PATCH',body:JSON.stringify({contact:$('dContact').value.trim(),note:$('dNote').value.trim()})});toast('Customer profile saved');await loadCustomers();await openCustomer(activeCustomerId)}catch(e){toast(e.message)}}
async function linkLicense(unlinkId=null){try{const licenseId=Number(unlinkId||$('linkLicenseSelect').value||0);if(!licenseId)throw new Error('Choose a license');await api(`/api/admin/customers/${activeCustomerId}/${unlinkId?'unlink-license':'link-license'}`,{method:'POST',body:JSON.stringify({licenseId})});toast(unlinkId?'License unlinked':'License linked');await Promise.all([loadLicenses(),loadCustomers(),loadSummary()]);await openCustomer(activeCustomerId)}catch(e){toast(e.message)}}
async function loadSettings(){const d=await api('/api/admin/settings'),s=Object.fromEntries(d.settings.map(x=>[x.key,x.value]));$('sMonthly').value=s.monthly_price_usd||20;$('sLifetime').value=s.lifetime_price_usd||s.annual_price_usd||100;$('sLimit').value=s.monthly_daily_limit||1500;$('sSupport').value=s.support_contact||'';$('sVersion').value=s.extension_version||'';$('sDownload').value=s.extension_download_url||''}
async function saveSettings(){try{await api('/api/admin/settings',{method:'PATCH',body:JSON.stringify({settings:{monthly_price_usd:$('sMonthly').value,lifetime_price_usd:$('sLifetime').value,monthly_daily_limit:$('sLimit').value,support_contact:$('sSupport').value,extension_version:$('sVersion').value,extension_download_url:$('sDownload').value}})});toast('Settings saved')}catch(e){toast(e.message)}}
async function loadOwner(){try{const d=await api('/api/admin/owner-access');$('ownerStatus').textContent=d.owner?`Status: ${d.owner.status} · updated ${date(d.owner.updated_at)}`:'No owner code yet'}catch(e){$('ownerStatus').textContent=e.message}}
async function rotateOwner(){if(!confirm('Create a new owner code? The old one stops working.'))return;try{const d=await api('/api/admin/owner-access/rotate',{method:'POST',body:'{}'});$('ownerCode').value=d.code;$('ownerCodeBox').classList.remove('hidden');await loadOwner()}catch(e){toast(e.message)}}
async function revokeOwner(){if(!confirm('Revoke owner code?'))return;try{await api('/api/admin/owner-access/revoke',{method:'POST',body:'{}'});$('ownerCodeBox').classList.add('hidden');await loadOwner()}catch(e){toast(e.message)}}
async function loadLogs(){const q=encodeURIComponent($('logSearch')?.value.trim()||''),d=await api('/api/admin/logs?q='+q);$('logsBody').innerHTML=(d.logs||[]).map(x=>`<tr><td>${date(x.created_at)}</td><td>${esc(x.event_type)}</td><td>${esc(x.target_type||'')} ${esc(x.target_id||'')}</td><td>${esc(x.result)}</td><td class="mono">${esc(x.metadata_json||'')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No logs</td></tr>'}
const loaders={dashboard:loadSummary,customers:loadCustomers,sales:loadSales,licenses:loadLicenses,support:loadSupport,owner:loadOwner,settings:loadSettings,logs:loadLogs};
async function openView(id){document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===id));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===id));const btn=document.querySelector(`[data-view="${id}"]`);$('title').textContent=btn?.textContent.trim()||id;try{await loaders[id]?.()}catch(e){toast(e.message)}}
async function refreshAll(){try{await loadCustomers();await Promise.all([loadSummary(),loadLicenses(),loadSales(),loadSupport(),loadSettings(),loadOwner(),loadLogs()])}catch(e){if(/UNAUTHORIZED/.test(e.message)){token='';sessionStorage.removeItem(TOKEN);showApp(false)}else toast(e.message)}}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)return void openView(nav.dataset.view);const jump=e.target.closest('[data-view-jump]');if(jump)return void openView(jump.dataset.viewJump);const oc=e.target.closest('[data-open-customer]');if(oc)return void openCustomer(oc.dataset.openCustomer);const ex=e.target.closest('[data-extend]');if(ex)return void licenseAction(ex.dataset.extend,'extend',ex.dataset.plan);const rv=e.target.closest('[data-revoke]');if(rv)return void licenseAction(rv.dataset.revoke,'revoke');const rs=e.target.closest('[data-reset]');if(rs)return void licenseAction(rs.dataset.reset,'reset-devices');const ul=e.target.closest('[data-unlink-license]');if(ul)return void linkLicense(ul.dataset.unlinkLicense)});
$('loginForm').addEventListener('submit',login);$('logout').addEventListener('click',logout);$('refreshCurrent').addEventListener('click',()=>{const id=document.querySelector('.view.active')?.id||'dashboard';openView(id)});$('toggleAddCustomer').addEventListener('click',()=>$('addCustomerBox').classList.toggle('hidden'));$('createCustomer').addEventListener('click',createCustomer);$('searchCustomers').addEventListener('click',loadCustomers);$('customerSearch').addEventListener('keydown',e=>{if(e.key==='Enter')loadCustomers()});$('toggleAddSale').addEventListener('click',()=>$('addSaleBox').classList.toggle('hidden'));$('createSale').addEventListener('click',createSale);$('searchSales').addEventListener('click',loadSales);$('generate').addEventListener('click',generate);$('searchLicenses').addEventListener('click',loadLicenses);$('saveSettings').addEventListener('click',saveSettings);$('rotateOwner').addEventListener('click',rotateOwner);$('revokeOwner').addEventListener('click',revokeOwner);$('refreshLogs').addEventListener('click',loadLogs);$('copyCodes').addEventListener('click',()=>copyField('generatedCodes'));$('copyOwner').addEventListener('click',()=>copyField('ownerCode'));$('closeDrawer').addEventListener('click',()=>$('customerDrawerBackdrop').classList.remove('open'));$('customerDrawerBackdrop').addEventListener('click',e=>{if(e.target===$('customerDrawerBackdrop'))$('customerDrawerBackdrop').classList.remove('open')});$('saveCustomerProfile').addEventListener('click',saveCustomerProfile);$('linkLicense').addEventListener('click',()=>linkLicense());
if(token){showApp(true);refreshAll()}else showApp(false);
})();
